KIV/FJP Compiler: FJP Namespace Reference
FJP Namespace Reference
Namespaces
CompilationErrors
Compilation error messages. These messages are used at compile time.
IOErrors
Error messages related to I/O errors.
RuntimeErrors
Runtime error messages. These messages are used at runtime.
Classes
class GeneratedCode
This class represents a code generated by the parser.
class ILexer
This class represents the interface of a lexer.
class IParser
This class represents the interface of a parser.
struct Instruction
Definition of an instruction.
class IVM
This class represents the interface of a virtual machine.
class Lexer
This class implements the functionality of a lexer.
class Logger
This class represents the logger of the application.
class Parser
This class implements the functionality of a parser.
struct Symbol
Definition of a symbol.
struct SymbolHash
Structure used for calculating the hash value of a symbol.
struct Frame
Definition of a "stack frame".
class SymbolTable
Definition of a symbol table.
struct Token
Definition of a token which is being passed from the lexer to the parser.
class VirtualMachine
Virtual machine used to execute the code generated by the parser.
Enumerations
enum OP_CODE {
LIT = 1 , OPR , LOD , STO ,
CAL , INC , JMP , JPC ,
SIO , LDA , STA
}
Enumeration of all instructions available.
enum OPRType {
OPR_RET = 0 , OPR_INVERT_VALUE , OPR_PLUS , OPR_MINUS ,
OPR_MUL , OPR_DIV , OPR_ODD , OPR_MOD ,
OPR_EQ , OPR_NEQ , OPR_LESS , OPR_LESS_EQ ,
OPR_GRT , OPR_GRT_EQ
}
Enumeration of different operations supported within this programming language.
enum SIO_TYPE { SIO_WRITE = 1 , SIO_READ , SIO_HALT }
Definition of all system I/O operations available within the program.
enum SymbolType {
SYMBOL_CONST = 1 , SYMBOL_INT , SYMBOL_BOOL , SYMBOL_INT_ARRAY ,
SYMBOL_BOOL_ARRAY , SYMBOL_FUNCTION , SYMBOL_LABEL , SYMBOL_NOT_FOUND
}
Enumeration of all different symbol types that may occur in the source code (input file).
enum TokenType {
IDENTIFIER , NUMBER , PLUS , MINUS ,
ASTERISK , SLASH , EQUALS , CONST_INIT ,
NOT_EQUALS , LESS , LESS_OR_EQUAL , GREATER ,
GREATER_OR_EQUAL , LEFT_PARENTHESIS , RIGHT_PARENTHESIS , LEFT_CURLY_BRACKET ,
RIGHT_CURLY_BRACKET , LEFT_SQUARED_BRACKET , RIGHT_SQUARED_BRACKET , LOGICAL_AND ,
LOGICAL_OR , COMMA , COLON , SEMICOLON ,
PERIOD , ASSIGN , IF , FOR ,
WHILE , DO , REPEAT , UNTIL ,
CONST , INT , BOOL , INT_ARRAY ,
BOOL_ARRAY , TRUE , FALSE , FUNCTION ,
WRITE , READ , ELSE , CALL ,
EXCLAMATION_MARK , QUESTION_MARK , GOTO , INSTANCEOF ,
START , FOREACH , SWITCH , CASE ,
BREAK , HASH_MARK , END , UNKNOWN
}
List of all tokens available in the application.
Functions
void exitProgramWithError (const char *errMsg, int errCode)
Exits the program with an error message.
void exitProgramWithError (const char *methodName, const char *errMsg, int errCode, int lineNumber)
Exits the program with an error message.
std::ostream & operator<< (std::ostream &out, const Instruction &instruction)
Prints out an instructions.
std::string op_code_to_str (OP_CODE op)
Converts an OP code into a string value.
std::ostream & operator<< (std::ostream &out, FJP::SymbolTable &symbolTable)
Prints out the contents of the symbol table.
std::ostream & operator<< (std::ostream &out, const FJP::Frame &frame)
Prints out the contents of a frame held in the symbol table.
std::ostream & operator<< (std::ostream &out, const FJP::Symbol &symbol)
Prints out a symbol.
std::ostream & operator<< (std::ostream &out, const FJP::SymbolType &symbolType)
Prints out a symbol type.
std::ostream & operator<< (std::ostream &out, const Token &token)
Prints out the token passed in as a parameter in a JSON format.
std::string token_type_to_str (TokenType tokenType)
Converts a token type into a string value.
Variables
static std::vector< std::pair< std::string, TokenType > > keywords
List of literal string values mapped onto their corresponding token values.
Enumeration Type Documentation
OP_CODE
enum FJP::OP_CODE
Enumeration of all instructions available.
These instructions are based on the PL0 instruction set. However, some additional custom instructions were added as well.
Enumerator
LIT
Pushes a constant on the top of the stack.
OPR
Performs an operation on the top of the stack.
LOD
Loads a value from an address to the top of the stack.
STO
Stores a value from the top of the stack to a particular address.
CAL
Calls a function.
INC
Allocates 'x' positions (slots/variables) on the stack.
JMP
Jumps to an address.
JPC
Conditional jump. It jumps if there is a 1 on the top of the stack (result of an operation).
SIO
System I/O operation (read/write).
LDA
Loads data on the top of the stack from an address which is stored on the top of the stack.
STA
Stores the value which is on the top of the stack at the address which is at the second position from the top of the stack.
Definition at line 10 of file isa.h.
                  {
         LIT = 1,
         OPR,
         LOD,
         STO,
         CAL,
         INC,
         JMP,
         JPC,
         SIO,
         LDA,
         STA
     };
OPRType
enum FJP::OPRType
Enumeration of different operations supported within this programming language.
These codes are used as a parameter of the OPR instruction.
Enumerator
OPR_RET
return
OPR_INVERT_VALUE
x = -x
OPR_PLUS
x + y
OPR_MINUS
x - y
OPR_MUL
x * y
OPR_DIV
x / y
OPR_ODD
x % 2
OPR_MOD
x % y
OPR_EQ
x == y
OPR_NEQ
x != y
OPR_LESS
x < y
OPR_LESS_EQ
x <= y
OPR_GRT
x > y
OPR_GRT_EQ
x >= y
Definition at line 27 of file isa.h.
                  {
         OPR_RET = 0,
         OPR_INVERT_VALUE,
         OPR_PLUS,
         OPR_MINUS,
         OPR_MUL,
         OPR_DIV,
         OPR_ODD,
         OPR_MOD,
         OPR_EQ,
         OPR_NEQ,
         OPR_LESS,
         OPR_LESS_EQ,
         OPR_GRT,
         OPR_GRT_EQ
     };
SIO_TYPE
enum FJP::SIO_TYPE
Definition of all system I/O operations available within the program.
These codes are used as a parameter of the SIO instruction.
Enumerator
SIO_WRITE
writes a number to the stdio
SIO_READ
reads a number from the stdio
SIO_HALT
halts the system (termination of the program)
Definition at line 47 of file isa.h.
                   {
         SIO_WRITE = 1,
         SIO_READ,
         SIO_HALT
     };
SymbolType
enum FJP::SymbolType
Enumeration of all different symbol types that may occur in the source code (input file).
Enumerator
SYMBOL_CONST
SYMBOL_INT
SYMBOL_BOOL
SYMBOL_INT_ARRAY
SYMBOL_BOOL_ARRAY
SYMBOL_FUNCTION
SYMBOL_LABEL
SYMBOL_NOT_FOUND
Definition at line 12 of file symbol_table.h.
                     {
         SYMBOL_CONST = 1,  // 'const'
         SYMBOL_INT,        // 'int'
         SYMBOL_BOOL,       // 'bool'
         SYMBOL_INT_ARRAY,  // 'int[]'
         SYMBOL_BOOL_ARRAY, // 'bool[]'
         SYMBOL_FUNCTION,   // 'function'
         SYMBOL_LABEL,      // 'label:'
         SYMBOL_NOT_FOUND   // used as an indicator in case a symbol was not found
     };
TokenType
enum FJP::TokenType
List of all tokens available in the application.
A stream of these tokens is used as an input for the parser.
Enumerator
IDENTIFIER
NUMBER
PLUS
MINUS
ASTERISK
SLASH
EQUALS
CONST_INIT
NOT_EQUALS
LESS
LESS_OR_EQUAL
GREATER
GREATER_OR_EQUAL
LEFT_PARENTHESIS
RIGHT_PARENTHESIS
LEFT_CURLY_BRACKET
RIGHT_CURLY_BRACKET
LEFT_SQUARED_BRACKET
RIGHT_SQUARED_BRACKET
LOGICAL_AND
LOGICAL_OR
COMMA
COLON
SEMICOLON
PERIOD
ASSIGN
IF
FOR
WHILE
DO
REPEAT
UNTIL
CONST
INT
BOOL
INT_ARRAY
BOOL_ARRAY
TRUE
FALSE
FUNCTION
WRITE
READ
ELSE
CALL
EXCLAMATION_MARK
QUESTION_MARK
GOTO
INSTANCEOF
START
FOREACH
SWITCH
CASE
BREAK
HASH_MARK
END
UNKNOWN
Definition at line 13 of file token.h.
                    {
         IDENTIFIER,            // _[a-zA-Z]*
         NUMBER,                // [0-9]+
         PLUS,                  // '+'
         MINUS,                 // '-'
         ASTERISK,              // '*'
         SLASH,                 // '/'
         EQUALS,                // '=='
         CONST_INIT,            // '='
         NOT_EQUALS,            // '!='
         LESS,                  // '<'
         LESS_OR_EQUAL,         // '<='
         GREATER,               // '>'
         GREATER_OR_EQUAL,      // '>='
         LEFT_PARENTHESIS,      // '('
         RIGHT_PARENTHESIS,     // ')'
         LEFT_CURLY_BRACKET,    // '{'
         RIGHT_CURLY_BRACKET,   // '}'
         LEFT_SQUARED_BRACKET,  // '['
         RIGHT_SQUARED_BRACKET, // ']'
         LOGICAL_AND,           // '&&'
         LOGICAL_OR,            // '||'
         COMMA,                 // ','
         COLON,                 // ':'
         SEMICOLON,             // ';'
         PERIOD,                // '.'
         ASSIGN,                // ':='
         IF,                    // 'if'
         FOR,                   // 'for'
         WHILE,                 // 'while'
         DO,                    // 'do'
         REPEAT,                // 'repeat'
         UNTIL,                 // 'until'
         CONST,                 // 'const'
         INT,                   // 'int'
         BOOL,                  // 'bool'
         INT_ARRAY,             // 'int[]'
         BOOL_ARRAY,            // 'bool[]'
         TRUE,                  // 'true'
         FALSE,                 // 'false'
         FUNCTION,              // 'function'
         WRITE,                 // 'write'
         READ,                  // 'read'
         ELSE,                  // 'else'
         CALL,                  // 'call'
         EXCLAMATION_MARK,      // '!'
         QUESTION_MARK,         // '?'
         GOTO,                  // 'goto'
         INSTANCEOF,            // 'instanceof'
         START,                 // 'START'
         FOREACH,               // 'foreach'
         SWITCH,                // 'switch'
         CASE,                  // 'case'
         BREAK,                 // 'break'
         HASH_MARK,             // '#'
         END,                   // 'END'
         UNKNOWN
     };
Function Documentation
exitProgramWithError() [1/2]
void FJP::exitProgramWithError (const char * errMsg, int errCode)
Exits the program with an error message.
Parameters
errMsg error message to be displayed to the user
errCode error code
Definition at line 5 of file errors.cpp.
{
     std::cout << errMsg << std::endl;
     // Exit the program.
     exit(errCode);
 }
Referenced by FJP::VirtualMachine::execute(), FJP::VirtualMachine::execute_INC(), FJP::VirtualMachine::execute_LDA(), FJP::VirtualMachine::execute_LIT(), FJP::VirtualMachine::execute_LOD(), FJP::VirtualMachine::execute_OPR(), FJP::VirtualMachine::execute_SIO(), FJP::VirtualMachine::execute_STA(), FJP::Lexer::getNextToken(), FJP::Lexer::init(), main(), FJP::Parser::parse(), FJP::Lexer::parseNextToken(), FJP::Lexer::processAllTokens(), FJP::Parser::processAssignment(), FJP::Parser::processCall(), FJP::Parser::processCases(), FJP::Parser::processCondition(), FJP::Parser::processConst(), FJP::Parser::processDoWhile(), FJP::Parser::processFactor(), FJP::Parser::processFor(), FJP::Parser::processForeach(), FJP::Parser::processFunction(), FJP::Parser::processGoto(), FJP::Parser::processIf(), FJP::Parser::processLabel(), FJP::Parser::processRead(), FJP::Parser::processRepeatUntil(), FJP::Parser::processSwitch(), FJP::Parser::processTernaryOperator(), FJP::Parser::processVariable(), FJP::Parser::processWhile(), FJP::Parser::processWrite(), FJP::Lexer::returnToPreviousToken(), FJP::Lexer::skipComments(), and FJP::Parser::storeCodeInstructionsIntoFile().
exitProgramWithError() [2/2]
void FJP::exitProgramWithError (const char * methodName, const char * errMsg, int errCode, int lineNumber)
Exits the program with an error message.
Additionally, it prints out the name of the method in which the error occurred. This piece of information is useful for debugging purposes.
Parameters
methodName the name of the method from which the program was terminated
errMsg error message to be displayed to the user
errCode error code
lineNumber line number within the source (input) program
Definition at line 12 of file errors.cpp.
{
     // [<method name>][#<line>] <error message>
     std::cout << "[" << methodName << "][#" << lineNumber <<  "] " << errMsg << std::endl;
     // Exit the program.
     exit(errCode);
 }
op_code_to_str()
std::string FJP::op_code_to_str (OP_CODE op)
Converts an OP code into a string value.
This method is used when an instruction is being printed out.
Parameters
op the OP code of the instruction
Returns
string value of the OP code
Definition at line 3 of file isa.cpp.
{
     switch (op) {
         case LIT:
             return "LIT";
         case OPR:
             return "OPR";
         case LOD:
             return "LOD";
         case STO:
             return "STO";
         case CAL:
             return "CAL";
         case INC:
             return "INC";
         case JMP:
             return "JMP";
         case JPC:
             return "JPC";
         case SIO:
             return "SIO";
         case LDA:
             return "LDA";
         case STA:
             return "STA";
     }
     return "unknown";
 }
References CAL, INC, JMP, JPC, LDA, LIT, LOD, OPR, SIO, STA, and STO.
Referenced by FJP::VirtualMachine::execute(), and operator<<().
operator<<() [1/6]
std::ostream & FJP::operator<< (std::ostream & out, const FJP::Frame & frame)
Prints out the contents of a frame held in the symbol table.
Parameters
out the output stream the frame will be printed out into.
frame the frame itself.
Returns
modified output stream (extended by the frame)
Definition at line 107 of file symbol_table.cpp.
{
     out << "------------\n";
     for (const auto &symbol : frame.symbols)
         out << symbol << '\n';
     out << "------------\n";
     return out;
 }
References FJP::Frame::symbols.
operator<<() [2/6]
std::ostream & FJP::operator<< (std::ostream & out, const FJP::Symbol & symbol)
Prints out a symbol.
Parameters
out the output stream the symbol will be printed out into.
symbol the symbol itself
Returns
modified output stream (extended by the symbol)
Definition at line 115 of file symbol_table.cpp.
{
     out << "type: "     << symbol.symbolType
         << " | name: "    << symbol.name
         << " | value: "   << symbol.value
         << " | level: "   << symbol.level
         << " | address: " << symbol.address;
     return out;
 }
References FJP::Symbol::address, FJP::Symbol::level, FJP::Symbol::name, FJP::Symbol::symbolType, and FJP::Symbol::value.
operator<<() [3/6]
std::ostream & FJP::operator<< (std::ostream & out, const FJP::SymbolType & symbolType)
Prints out a symbol type.
Parameters
out the output stream the symbol type will be printed out into.
symbolType the symbol type itself
Returns
modified output stream (extended by symbol type)
Definition at line 124 of file symbol_table.cpp.
{
     switch (symbolType) {
         case FJP::SymbolType::SYMBOL_CONST:
             out << "const";
             break;
         case FJP::SymbolType::SYMBOL_INT:
             out << "int";
             break;
         case FJP::SymbolType::SYMBOL_BOOL:
             out << "bool";
             break;
         case FJP::SymbolType::SYMBOL_FUNCTION:
             out << "function";
             break;
         case FJP::SymbolType::SYMBOL_NOT_FOUND:
             out << "not-found";
             break;
         default:
             out << "unknown";
     }
     return out;
 }
References SYMBOL_BOOL, SYMBOL_CONST, SYMBOL_FUNCTION, SYMBOL_INT, and SYMBOL_NOT_FOUND.
operator<<() [4/6]
std::ostream & FJP::operator<< (std::ostream & out, const Instruction & instruction)
Prints out an instructions.
Parameters
out the output stream the instruction will be printed out into.
instruction the instruction itself
Returns
modified output stream (extended by the instruction)
Definition at line 31 of file isa.cpp.
{
     out << op_code_to_str(instruction.op) << " "
         << instruction.l << " "
         << instruction.m;
     return out;
 }
References FJP::Instruction::l, FJP::Instruction::m, FJP::Instruction::op, and op_code_to_str().
operator<<() [5/6]
std::ostream & FJP::operator<< (std::ostream & out, const Token & token)
Prints out the token passed in as a parameter in a JSON format.
Parameters
out output stream
token token to be printed to the stream
Returns
modified output stream (extended by the token)
Definition at line 5 of file token.cpp.
{
     // Prints out the token into the output stream in a JSON format.
     out << "{\n";
     out << "    \"typeId\": " << "\""     << token.tokenType                    << "\"" << ",\n";
     out << "    \"type\": " << "\""       << token_type_to_str(token.tokenType) << "\"" << ",\n";
     out << "    \"lineNumber\": " << "\"" << token.lineNumber                   << "\"" << ",\n";
     out << "    \"value\": " << "\""      << token.value                        << "\"" << "\n";
     out << "}";
     // Return the output stream.
     return out;
 }
References FJP::Token::lineNumber, token_type_to_str(), FJP::Token::tokenType, and FJP::Token::value.
operator<<() [6/6]
std::ostream & FJP::operator<< (std::ostream & out, FJP::SymbolTable & symbolTable)
Prints out the contents of the symbol table.
Parameters
out the output stream the symbol table will be printed out into.
symbolTable the symbol table itself
Returns
modified output stream (extended by the symbol table)
Definition at line 98 of file symbol_table.cpp.
{
     out << "============\n";
     auto frames = symbolTable.getFrames();
     for (const auto& frame : frames)
         out << frame;
     out << "============\n";
     return out;
 }
References FJP::SymbolTable::getFrames().
token_type_to_str()
std::string FJP::token_type_to_str (FJP::TokenType tokenType)
Converts a token type into a string value.
This function is used when printing tokens into the output stream.
Parameters
tokenType type of a token
Returns
token type converted into a string value
Definition at line 18 of file token.cpp.
{
     // Tries to find a token by its corresponding string value (using the keywords list)
     auto match = std::find_if(keywords.begin(), keywords.end(), [&](const auto &keyword) {
        return keyword.second == tokenType;
     });
     // If such token has not been found, it has to be either an
     // identifier or a number because those are not listed out due to
     // their variability
     if (match != keywords.end())
         return match->first;
     switch (tokenType) {
         case IDENTIFIER:
             return "identifier";
         case NUMBER:
             return "number";
         default:
             return "unknown"; // It should never get here
     }
     // This is here just so the compiler does not complain about
     // a missing return value at the end of the method.
     return "unknown";
 }
References IDENTIFIER, keywords, and NUMBER.
Referenced by operator<<().
Variable Documentation
keywords
std::vector<std::pair<std::string, TokenType> > FJP::keywords static
List of literal string values mapped onto their corresponding token values.
This std::vector will be sorted out upon the lexer instantiation. The reason for sorting these values is to prevent mistreating tokens which happen to be a prefix of another token. For example, ':' and ':='. Therefore, the list will be sorted in a descending order by the token string value.
Definition at line 84 of file token.h.
Referenced by FJP::Lexer::Lexer(), FJP::Lexer::parseNextToken(), and token_type_to_str().