KIV/FJP Compiler: FJP::Parser Class Reference
FJP::Parser Class Reference
This class implements the functionality of a parser.
#include <parser.h>
Public Member Functions
FJP::GeneratedCode parse (FJP::ILexer *lexer, bool debug=false) override
Performs recursive descent and generates code for the virtual machine.
Static Public Member Functions
static Parser * getInstance ()
Return the instance of the class.
Private Member Functions
Parser ()
Constructor - creates an instance of the class.
Parser (Parser &)=delete
Deleted copy constructor of the class.
void operator= (Parser const &)=delete
Deleted assign operator of the class.
void storeCodeInstructionsIntoFile ()
Stores the instructions of the output code into a file.
void processBlock ()
Processes a 'block' (recursive descent).
void processConst ()
Processes a 'const' (recursive descent).
void processVariable (int &frameVariableCount)
Processes a 'variable' (recursive descent).
void processFunction ()
Processes a 'function' (recursive descent).
void processStatement ()
Processes a 'statement' (recursive descent).
void processAssignment (bool expectSemicolon=true)
Processes an 'assignment' (recursive descent).
void processExpression ()
Processes an 'expression' (recursive descent).
void processCall ()
Processes a 'call' (recursive descent).
void processScope ()
Processes a 'scope' (recursive descent).
void processIf ()
Processes an 'if' statement (recursive descent).
void processCondition ()
Processes a 'condition' (recursive descent).
void processWhile ()
Processes a 'while' loop (recursive descent).
void processDoWhile ()
Processes a 'do-while' loop (recursive descent).
void processFor ()
Processes a 'for' loop (recursive descent).
void processRepeatUntil ()
Processes a 'repeat-until' loop (recursive descent).
void processForeach ()
Processes a 'foreach' loop (recursive descent).
void processSwitch ()
Processes a 'switch' statement (recursive descent).
void processTernaryOperator ()
Processes a 'ternary operator' (recursive descent).
void processCases (Symbol &variable, std::list< int > &breaks)
Processes a 'case' in a switch statement (recursive descent).
void processLabel (const std::string label)
Processes a 'label' (recursive descent).
void processGoto ()
Processes a 'goto' statement (recursive descent).
void processTerm ()
Processes a 'term' (recursive descent).
void processFactor ()
Processes a 'factor' (recursive descent).
void processRead ()
Processes a 'read' operation (recursive descent).
void processWrite ()
Processes a 'write' operation (recursive descent).
Private Attributes
FJP::ILexer * lexer
An instance of Lexer (set upon initialization).
FJP::GeneratedCode generatedCode
Output of the parser - generated code.
FJP::SymbolTable symbolTable
Symbol table used during the recursive descent algorithm.
FJP::Token token
Current token retrieved from the lexer.
int nextFreeAddress
Next free address within one function call.
std::map< std::string, std::list< int > > undefinedLabels
Associative array of labels that need to be defined.
FJP::Symbol lastProcessVariable
Last processed variable - used in multi assignment.
Static Private Attributes
static constexpr int DEFAULT_INT_VALUE = 0
Default value of an integer variable.
static constexpr int DEFAULT_BOOL_VALUE = 0
Default value of a bool variable (false).
static constexpr int ERR_CODE = 2
Parser error code (used when terminating the application).
static constexpr const char * OUTPUT_FILE = "code.pl0"
Output file containing the stack trace as the program is being executed.
static constexpr int ADDRESS_LEN = 3
Number of digits an address is aligned to when being printed out.
static constexpr int FRAME_INIT_VAR_COUNT = 4
Number of variables stored onto the stack upon a function call.
static Parser * instance = nullptr
The instance of the class.
Detailed Description
This class implements the functionality of a parser.
It uses the lexer and its stream of tokens as an input.
Definition at line 15 of file parser.h.
Constructor & Destructor Documentation
Parser() [1/2]
FJP::Parser::Parser () private
Constructor - creates an instance of the class.
Definition at line 25 of file parser.cpp.
                   : lexer(nullptr), nextFreeAddress(0) {
 }
Referenced by getInstance().
Parser() [2/2]
FJP::Parser::Parser (Parser &) private delete
Deleted copy constructor of the class.
Member Function Documentation
getInstance()
FJP::Parser * FJP::Parser::getInstance () static
Return the instance of the class.
Returns
the instance of the class
Definition at line 18 of file parser.cpp.
{
     if (instance == nullptr) {
         instance = new Parser;
     }
     return instance;
 }
References instance, and Parser().
Referenced by main().
operator=()
void FJP::Parser::operator= (Parser const &) private delete
Deleted assign operator of the class.
parse()
FJP::GeneratedCode FJP::Parser::parse (FJP::ILexer * lexer, bool debug = false) override virtual
Performs recursive descent and generates code for the virtual machine.
Parameters
lexer instance of Lexer (getting a stream of tokens)
debug flag if we want to output the program into a file
Returns
generated code written in an extended/customized version of PL0
Implements FJP::IParser.
Definition at line 28 of file parser.cpp.
{
     // Make sure that the lexer is not nullptr.
     assert(lexer != nullptr);
     this->lexer = lexer;
     generatedCode = FJP::GeneratedCode();
     // START
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::START) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_37, ERR_CODE, token.lineNumber);
     }
     // <block>
     token = lexer->getNextToken();
     processBlock();
     // END
     if (token.tokenType != FJP::TokenType::END) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_36, ERR_CODE, token.lineNumber);
     }
     // Make sure that all undefined labels were eventually defined.
     for (auto &label : undefinedLabels) {
         std::string errMsg = "label '";
         errMsg += label.first;
         errMsg += "' has not been defined";
         FJP::exitProgramWithError(__FUNCTION__, errMsg.c_str(), ERR_CODE, token.lineNumber);
     }
     // If the debug flag is on, spill the generated code out into a file.
     if (debug == true) {
         storeCodeInstructionsIntoFile();
     }
     // Return the generated program co it can be executed by the virtual machine.
     return generatedCode;
 }
References FJP::END, FJP::CompilationErrors::ERROR_36, FJP::CompilationErrors::ERROR_37, FJP::exitProgramWithError(), FJP::ILexer::getNextToken(), and FJP::START.
processAssignment()
void FJP::Parser::processAssignment (bool expectSemicolon = true) private
Processes an 'assignment' (recursive descent).
Parameters
expectSemicolon flag saying if there should a semicolon at the end of the assignment
Definition at line 457 of file parser.cpp.
{
     // <identifier>
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         return;
     }
     // Make sure the identifier exists in the symbol table. If it's not found,
     // it is treated as a label (goto).
     // label:
     FJP::Symbol variable = symbolTable.findSymbol(token.value);
     if (variable.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         // Process the label and return the function.
         processLabel(token.value);
         return;
     }
     bool isAnotherAssign = true;
     switch (variable.symbolType) {
         // If the identifier is an integer or bool.
         case FJP::SymbolType::SYMBOL_INT:
         case FJP::SymbolType::SYMBOL_BOOL:
             // ':='
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::ASSIGN) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_14, ERR_CODE, token.lineNumber);
             }
             // <identifier>
             token = lexer->getNextToken();
             if (token.tokenType == FJP::TokenType::IDENTIFIER) {
                 // Check if the token two steps ahead is also an identifier. If it's
                 // not an identifier, it has to be treated as an expression.
                 // For example <identifier> := <identifier> or <identifier> := <identifier> + 55
                 token = lexer->getNextToken();
                 if (token.tokenType != FJP::TokenType::ASSIGN) {
                     lexer->returnToPreviousToken();
                     lexer->returnToPreviousToken();
                     token = lexer->getNextToken();
                     isAnotherAssign = false;
                 }
                 if (isAnotherAssign) {
                     // Recursively process another assignment.
                     processAssignment();
                     // Copy the value from the previous variable into the current one (chain of assignments).
                     generatedCode.addInstruction({FJP::OP_CODE::LOD, lastProcessVariable.level, lastProcessVariable.address});
                     if (variable.symbolType == FJP::SymbolType::SYMBOL_BOOL) {
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0 });
                         generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ });
                     }
                     generatedCode.addInstruction({ FJP::OP_CODE::STO, symbolTable.getDepthLevel() - variable.level, variable.address });
                 }
             }
             // <expression>
             processExpression();
             // If the identifier was a boolean, convert the result of the expression into 1/0.
             if (variable.symbolType == FJP::SymbolType::SYMBOL_BOOL) {
                 generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0 });
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ });
             }
             generatedCode.addInstruction({ FJP::OP_CODE::STO, symbolTable.getDepthLevel() - variable.level, variable.address });
             lastProcessVariable = variable;
             break;
         // If the symbol is an array.
         case FJP::SymbolType::SYMBOL_INT_ARRAY:
         case FJP::SymbolType::SYMBOL_BOOL_ARRAY:
             // '['
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::LEFT_SQUARED_BRACKET) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_17, ERR_CODE, token.lineNumber);
             }
             // <expression>
             token = lexer->getNextToken();
             processExpression();
             // Calculate the address of the element in the array (base + offset).
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, variable.address });
             generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS });
             // ']'
             if (token.tokenType != FJP::TokenType::RIGHT_SQUARED_BRACKET) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_16, ERR_CODE, token.lineNumber);
             }
             // ':='
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::ASSIGN) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_14, ERR_CODE, token.lineNumber);
             }
             // <expression>
             token = lexer->getNextToken();
             processExpression();
             // If the identifier was a boolean, convert the result of the expression into 1/0.
             if (variable.symbolType == FJP::SymbolType::SYMBOL_BOOL_ARRAY) {
                 generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0 });
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ });
             }
             generatedCode.addInstruction({FJP::OP_CODE::STA, symbolTable.getDepthLevel() - variable.level, 0});
             break;
         default:
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_29, ERR_CODE, token.lineNumber);
             break;
     }
     // ';'
     if (expectSemicolon) {
         if (token.tokenType != FJP::TokenType::SEMICOLON) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
         }
         // Load up the next token, so it can be processed.
         token = lexer->getNextToken();
     }
 }
References FJP::Symbol::address, FJP::ASSIGN, FJP::CompilationErrors::ERROR_14, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_16, FJP::CompilationErrors::ERROR_17, FJP::CompilationErrors::ERROR_29, FJP::exitProgramWithError(), FJP::IDENTIFIER, FJP::LEFT_SQUARED_BRACKET, FJP::Symbol::level, FJP::LIT, FJP::LOD, FJP::OPR, FJP::OPR_NEQ, FJP::OPR_PLUS, FJP::RIGHT_SQUARED_BRACKET, FJP::SEMICOLON, FJP::STA, FJP::STO, FJP::SYMBOL_BOOL, FJP::SYMBOL_BOOL_ARRAY, FJP::SYMBOL_INT, FJP::SYMBOL_INT_ARRAY, FJP::SYMBOL_NOT_FOUND, and FJP::Symbol::symbolType.
processBlock()
void FJP::Parser::processBlock () private
Processes a 'block' (recursive descent).
Definition at line 93 of file parser.cpp.
{
     // Default allocation size of the frame - 0, base(l, EBP), EBP, EIP.
     int frameVariableCount = FRAME_INIT_VAR_COUNT;
     // Address of the next variable that will be created within the frame.
     nextFreeAddress = FRAME_INIT_VAR_COUNT;
     symbolTable.createFrame();
     // Added a new instruction that will allocate a certain amount
     // of variable on the stack. The particular value will be specified
     // once the block has been completely parsed.
     generatedCode.addInstruction({FJP::OP_CODE::INC, 0, 0});
     int incInstructionAddress = generatedCode.getSize() - 1;
     // Process all const and variable declarations.
     processConst();
     processVariable(frameVariableCount);
     // Add a JMP instruction, so we can skip all functions and jump straight
     // at the first instruction of the "main function".
     int jmpAddress = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
     // Process all functions.
     processFunction();
     // Now we know the first address of the actual program,
     // so we can set the jump address of the instruction that we added before.
     generatedCode[jmpAddress].m = generatedCode.getSize();
     // Also, since all variables must have been already declared, we can
     // specifically say how many variables need to be allocated on the stack.
     generatedCode[incInstructionAddress].m = frameVariableCount;
     // Process a statements.
     processStatement();
     // Destroy the frame since we're about to return from the function.
     nextFreeAddress -= FRAME_INIT_VAR_COUNT;
     symbolTable.destroyFrame();
     // Add a return operation as a return from the function.
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_RET});
 }
References FJP::INC, FJP::JMP, FJP::OPR, and FJP::OPR_RET.
processCall()
void FJP::Parser::processCall () private
Processes a 'call' (recursive descent).
Definition at line 602 of file parser.cpp.
{
     // 'call'
     if (token.tokenType != FJP::TokenType::CALL) {
         return;
     }
     // <identifier>
     token = lexer->getNextToken();
     Symbol function = symbolTable.findSymbol(token.value);
     // Make sure the symbol exists in the symbol table.
     if (function.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
     }
     // Make sure the identifier is a function.
     if (function.symbolType != FJP::SymbolType::SYMBOL_FUNCTION) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_23, ERR_CODE, token.lineNumber);
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // ')'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Create a JMP instruction to jump to the first address of the function.
     generatedCode.addInstruction({FJP::OP_CODE::CAL, symbolTable.getDepthLevel() - function.level, function.value});
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::CAL, FJP::CALL, FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_23, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::LEFT_PARENTHESIS, FJP::RIGHT_PARENTHESIS, FJP::SEMICOLON, FJP::SYMBOL_FUNCTION, and FJP::SYMBOL_NOT_FOUND.
processCases()
void FJP::Parser::processCases (Symbol & variable, std::list< int > & breaks) private
Processes a 'case' in a switch statement (recursive descent).
Parameters
variable the main variable used in the switch statement
breaks list of all break statements within the switch statement
Definition at line 1137 of file parser.cpp.
{
     // case
     if (token.tokenType != FJP::TokenType::CASE) {
         return;
     }
     // Check if the token is indeed a literal (number, true, false).
     token = lexer->getNextToken();
     int token_value;
     if (token.tokenType != FJP::TokenType::NUMBER &&
         token.tokenType != FJP::TokenType::TRUE &&
         token.tokenType != FJP::TokenType::FALSE) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_34, ERR_CODE, token.lineNumber);
     }
     // Parse the literal. If it is a number, convert it into an integer, and if
     // it is a boolean, convert it into 1/0.
     if (token.tokenType == FJP::TokenType::NUMBER) {
         token_value = atoi(token.value.c_str());
     } else {
         token_value = token.value == "true";
     }
     // Make sure the literal is the same datatype as the variable used in the switch statement.
     if (((variable.symbolType == SYMBOL_INT) && token.tokenType != NUMBER) ||
         ((variable.symbolType == SYMBOL_BOOL) && !(token.tokenType == TRUE || token.tokenType == FALSE))) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_35, ERR_CODE, token.lineNumber);
     }
     // ':'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::COLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_11, ERR_CODE, token.lineNumber);
     }
     // Compare the literal against the variable used in the switch statement.
     generatedCode.addInstruction({FJP::OP_CODE::LOD, symbolTable.getDepthLevel() - variable.level, variable.address});
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, token_value});
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_EQ});
     // If it doesn't match up, skip the body of the case statement and jump onto the next case.
     int jpc_address = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, 0});
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // Set the jump address to jump to in case the literal doesn't mach the value of the variable
     // used in the switch statement (jump onto the next case).
     generatedCode[jpc_address].m = generatedCode.getSize();
     // <break>
     if (token.tokenType == FJP::TokenType::BREAK) {
         // Add the address of the break statement to the list of all breaks.
         // The jump address will be known after the entire switch has been processed.
         breaks.push_back(generatedCode.getSize());
         generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
         // ';'
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::SEMICOLON) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
         }
         // Also, we need to skip the break itself in case we're jumping onto the next case.
         token = lexer->getNextToken();
         generatedCode[jpc_address].m++;
     }
     // Process the next statement.
     processCases(variable, breaks);
 }
References FJP::Symbol::address, FJP::BREAK, FJP::CASE, FJP::COLON, FJP::CompilationErrors::ERROR_11, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_34, FJP::CompilationErrors::ERROR_35, FJP::exitProgramWithError(), FJP::FALSE, FJP::JMP, FJP::JPC, FJP::Symbol::level, FJP::LIT, FJP::LOD, FJP::NUMBER, FJP::OPR, FJP::OPR_EQ, FJP::SEMICOLON, FJP::SYMBOL_BOOL, FJP::SYMBOL_INT, FJP::Symbol::symbolType, and FJP::TRUE.
processCondition()
void FJP::Parser::processCondition () private
Processes a 'condition' (recursive descent).
Definition at line 1258 of file parser.cpp.
{
     // '!'
     if (token.tokenType == FJP::TokenType::EXCLAMATION_MARK) {
         // <expression>
         token = lexer->getNextToken();
         processExpression();
         // Compare the result of the expression to 0, and store the result
         // of the comparison on the top of the stack.
         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0});
         generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_EQ});
     } else {
         // <expression>
         processExpression();
         FJP::OPRType instructionType = FJP::OPRType::OPR_RET;
         FJP::TokenType logicalOperation = FJP::TokenType::UNKNOWN;
         switch (token.tokenType) {
             // '=='
             case FJP::TokenType::EQUALS:
                 instructionType = FJP::OPRType::OPR_EQ;
                 break;
             // '!='
             case FJP::TokenType::NOT_EQUALS:
                 instructionType = FJP::OPRType::OPR_NEQ;
                 break;
             // '<'
             case FJP::TokenType::LESS:
                 instructionType = FJP::OPRType::OPR_LESS;
                 break;
             // '<='
             case FJP::TokenType::LESS_OR_EQUAL:
                 instructionType = FJP::OPRType::OPR_LESS_EQ;
                 break;
             // '>'
             case FJP::TokenType::GREATER:
                 instructionType = FJP::OPRType::OPR_GRT;
                 break;
             // '>='
             case FJP::TokenType::GREATER_OR_EQUAL:
                 instructionType = FJP::OPRType::OPR_GRT_EQ;
                 break;
             // '&&'
             case FJP::TokenType::LOGICAL_AND:
             // '||'
             case FJP::TokenType::LOGICAL_OR:
                 logicalOperation = token.tokenType;
                 break;
             default:
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_28, ERR_CODE, token.lineNumber);
         }
         // <expression>
         token = lexer->getNextToken();
         processExpression();
         // Based on the type of comparison, person an operation
         // wit the two values (the results of the two expressions)
         // on the top of the stack. The result is going to be 1/0.
         switch (logicalOperation) {
             // If the operation is something other than '&&' or '||'.
             case FJP::TokenType::UNKNOWN:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, instructionType});
                 break;
             // '&&' - it needs to be done only by the operations supported by PL0
             case FJP::TokenType::LOGICAL_AND:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_MUL});
                 generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0});
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ});
                 break;
             // '||' - it needs to be done only by the operations supported by PL0
             case FJP::TokenType::LOGICAL_OR:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
                 generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0});
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ});
                 break;
             default:
                 break;
         }
     }
 }
References FJP::EQUALS, FJP::CompilationErrors::ERROR_28, FJP::EXCLAMATION_MARK, FJP::exitProgramWithError(), FJP::GREATER, FJP::GREATER_OR_EQUAL, FJP::LESS, FJP::LESS_OR_EQUAL, FJP::LIT, FJP::LOGICAL_AND, FJP::LOGICAL_OR, FJP::NOT_EQUALS, FJP::OPR, FJP::OPR_EQ, FJP::OPR_GRT, FJP::OPR_GRT_EQ, FJP::OPR_LESS, FJP::OPR_LESS_EQ, FJP::OPR_MUL, FJP::OPR_NEQ, FJP::OPR_PLUS, FJP::OPR_RET, and FJP::UNKNOWN.
processConst()
void FJP::Parser::processConst () private
Processes a 'const' (recursive descent).
Definition at line 140 of file parser.cpp.
{
     // const
     while (token.tokenType == FJP::TokenType::CONST) {
         token = lexer->getNextToken();
         int value;
         std::string identifier;
         FJP::TokenType dataType = token.tokenType;
         // int / bool
         if (!(dataType == FJP::TokenType::INT || dataType == FJP::TokenType::BOOL)) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_29, ERR_CODE, token.lineNumber);
         }
         while (true) {
             // identifier
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::IDENTIFIER) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_44, ERR_CODE, token.lineNumber);
                 return;
             }
             // Make sure the name of the identifier isn't already taken.
             identifier = token.value;
             if (symbolTable.existsSymbol(identifier) == true) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_43, ERR_CODE, token.lineNumber);
                 return;
             }
             // '='
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::CONST_INIT) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_21, ERR_CODE, token.lineNumber);
                 return;
             }
             token = lexer->getNextToken();
             switch (dataType) {
                 // If the type is an integer, the next token has to be a number.
                 case FJP::TokenType::INT:
                     if (token.tokenType != FJP::TokenType::NUMBER) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_07, ERR_CODE, token.lineNumber);
                     }
                     // Convert the token value into an int and set to the identifier in the symbol table.
                     value = atoi(token.value.c_str());
                     symbolTable.addSymbol({FJP::SymbolType::SYMBOL_CONST, identifier, value, 0, 0, 0});
                     break;
                 // If the type is a bool, the next token has to be either true or false.
                 case FJP::TokenType::BOOL:
                     if (!(token.tokenType == FJP::TokenType::TRUE || token.tokenType == FJP::TokenType::FALSE)) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_10, ERR_CODE, token.lineNumber);
                     }
                     // Convert the token value into an int (0 = false, 1 = true) and set to the identifier in the symbol table.
                     symbolTable.addSymbol({FJP::SymbolType::SYMBOL_CONST, identifier, token.tokenType == FJP::TokenType::TRUE, 0, 0, 0});
                     break;
                 default:
                     break;
             }
             // ','
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::COMMA)
                 break;
         }
         // ';'
         if (token.tokenType != FJP::TokenType::SEMICOLON) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
         }
         // Read the next token so it can be processed.
         token = lexer->getNextToken();
     }
 }
References FJP::BOOL, FJP::COMMA, FJP::CONST, FJP::CONST_INIT, FJP::CompilationErrors::ERROR_07, FJP::CompilationErrors::ERROR_10, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_21, FJP::CompilationErrors::ERROR_29, FJP::CompilationErrors::ERROR_43, FJP::CompilationErrors::ERROR_44, FJP::exitProgramWithError(), FJP::FALSE, FJP::IDENTIFIER, FJP::INT, FJP::NUMBER, FJP::SEMICOLON, FJP::SYMBOL_CONST, and FJP::TRUE.
processDoWhile()
void FJP::Parser::processDoWhile () private
Processes a 'do-while' loop (recursive descent).
Definition at line 759 of file parser.cpp.
{
     // do
     if (token.tokenType != FJP::TokenType::DO) {
         return;
     }
     // Start address of the body of the do-while loop.
     int doWhileStart = generatedCode.getSize();
     // '{'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_18, ERR_CODE, token.lineNumber);
     }
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // '}'
     if (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_19, ERR_CODE, token.lineNumber);
     }
     // 'while'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::WHILE) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_38, ERR_CODE, token.lineNumber);
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // <condition>
     token = lexer->getNextToken();
     processCondition();
     // If the result of condition is true (1) jump to the first address
     // of the body of the do-while loop.
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0});
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_EQ});
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, doWhileStart });
     // ')'
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::DO, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_18, FJP::CompilationErrors::ERROR_19, FJP::CompilationErrors::ERROR_38, FJP::exitProgramWithError(), FJP::JPC, FJP::LEFT_CURLY_BRACKET, FJP::LEFT_PARENTHESIS, FJP::LIT, FJP::OPR, FJP::OPR_EQ, FJP::RIGHT_CURLY_BRACKET, FJP::RIGHT_PARENTHESIS, FJP::SEMICOLON, and FJP::WHILE.
processExpression()
void FJP::Parser::processExpression () private
Processes an 'expression' (recursive descent).
Definition at line 1382 of file parser.cpp.
{
     // '#' -> treat it as a ternary operator
     if (token.tokenType == FJP::TokenType::HASH_MARK) {
         processTernaryOperator();
         return;
     }
     FJP::TokenType currTokenType;
     // '+' / '-'
     if (token.tokenType == FJP::TokenType::PLUS || token.tokenType == FJP::TokenType::MINUS) {
         currTokenType = token.tokenType;
         // <term>
         token = lexer->getNextToken();
         processTerm();
         // If the sign is a minus, invert the value on the top of the stack.
         if (currTokenType == FJP::TokenType::MINUS) {
             generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_INVERT_VALUE});
         }
     } else {
         // <term>
         processTerm();
     }
     while (token.tokenType == FJP::TokenType::PLUS || token.tokenType == FJP::TokenType::MINUS) {
         currTokenType = token.tokenType;
         // <term>
         token = lexer->getNextToken();
         processTerm();
         // Add instruction to cary out the operation on top of the stack.
         switch (currTokenType) {
             // '+'
             case FJP::TokenType::PLUS:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
                 break;
             // '-'
             case FJP::TokenType::MINUS:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_MINUS});
                 break;
             default:
                 break;
         }
     }
 }
References FJP::HASH_MARK, FJP::MINUS, FJP::OPR, FJP::OPR_INVERT_VALUE, FJP::OPR_MINUS, FJP::OPR_PLUS, and FJP::PLUS.
processFactor()
void FJP::Parser::processFactor () private
Processes a 'factor' (recursive descent).
Definition at line 1461 of file parser.cpp.
{
     FJP::Symbol symbol;
     int numberValue;
     bool nextToken = true;
     switch (token.tokenType) {
         // <identifier>
         case FJP::TokenType::IDENTIFIER:
             // Make sure the identifier exists within the symbol table.
             symbol = symbolTable.findSymbol(token.value);
             if (symbol.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
             }
             // Check if the next token is 'instanceof'
             token = lexer->getNextToken();
             if (token.tokenType == FJP::TokenType::INSTANCEOF) {
                 token = lexer->getNextToken();
                 switch (token.tokenType) {
                     // instanceof 'int'
                     case FJP::TokenType::INT:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.symbolType == FJP::SYMBOL_INT});
                         break;
                     // instanceof 'bool'
                     case FJP::TokenType::BOOL:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.symbolType == FJP::SYMBOL_BOOL});
                         break;
                     // instanceof 'int[]'
                     case FJP::TokenType::INT_ARRAY:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.symbolType == FJP::SYMBOL_INT_ARRAY});
                         break;
                     // instanceof 'bool[]'
                     case FJP::TokenType::BOOL_ARRAY:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.symbolType == FJP::SYMBOL_BOOL_ARRAY});
                         break;
                     // instanceof 'function'
                     case FJP::TokenType::FUNCTION:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.symbolType == FJP::SYMBOL_FUNCTION});
                         break;
                     default:
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_31, ERR_CODE, token.lineNumber);
                         break;
                 }
             } else {
                 // Do not load up the next token.
                 nextToken = false;
                 // Check the type of the identifier
                 switch (symbol.symbolType) {
                     // <int/bool>
                     case FJP::SymbolType::SYMBOL_INT:
                     case FJP::SymbolType::SYMBOL_BOOL:
                         generatedCode.addInstruction({FJP::OP_CODE::LOD, symbolTable.getDepthLevel() - symbol.level, symbol.address});
                         break;
                     // <const>
                     case FJP::SymbolType::SYMBOL_CONST:
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.value});
                         break;
                     // <int[]/bool[]>
                     case FJP::SymbolType::SYMBOL_INT_ARRAY:
                     case FJP::SymbolType::SYMBOL_BOOL_ARRAY:
                         // '['
                         if (token.tokenType != FJP::TokenType::LEFT_SQUARED_BRACKET) {
                             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_17, ERR_CODE, token.lineNumber);
                         }
                         // <expression>
                         token = lexer->getNextToken();
                         processExpression();
                         // Calculate the address of the element within the array. Add up the base address and the index.
                         generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.address});
                         generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
                         // Load the value to the top of the stack.
                         generatedCode.addInstruction({FJP::OP_CODE::LDA, symbolTable.getDepthLevel() - symbol.level, 0});
                         // ']'
                         if (token.tokenType != FJP::TokenType::RIGHT_SQUARED_BRACKET) {
                             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_16, ERR_CODE, token.lineNumber);
                         }
                         token = lexer->getNextToken();
                         break;
                     default:
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_29, ERR_CODE, token.lineNumber);
                         break;
                 }
             }
             break;
         // <number>
         case FJP::TokenType::NUMBER:
             numberValue = atoi(token.value.c_str());
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, numberValue});
             break;
         // <true/false>
         case FJP::TokenType::TRUE:
         case FJP::TokenType::FALSE:
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, token.tokenType == FJP::TokenType::TRUE});
             break;
         // '('
         case FJP::TokenType::LEFT_PARENTHESIS:
             // <expression>
             token = lexer->getNextToken();
             processExpression();
             // ')'
             if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
             }
             break;
         default:
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_22, ERR_CODE, token.lineNumber);
             break;
     }
     if (nextToken == true) {
         token = lexer->getNextToken();
     }
 }
References FJP::Symbol::address, FJP::BOOL, FJP::BOOL_ARRAY, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_16, FJP::CompilationErrors::ERROR_17, FJP::CompilationErrors::ERROR_22, FJP::CompilationErrors::ERROR_29, FJP::CompilationErrors::ERROR_31, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::FALSE, FJP::FUNCTION, FJP::IDENTIFIER, FJP::INSTANCEOF, FJP::INT, FJP::INT_ARRAY, FJP::LDA, FJP::LEFT_PARENTHESIS, FJP::LEFT_SQUARED_BRACKET, FJP::Symbol::level, FJP::LIT, FJP::LOD, FJP::NUMBER, FJP::OPR, FJP::OPR_PLUS, FJP::RIGHT_PARENTHESIS, FJP::RIGHT_SQUARED_BRACKET, FJP::SYMBOL_BOOL, FJP::SYMBOL_BOOL_ARRAY, FJP::SYMBOL_CONST, FJP::SYMBOL_FUNCTION, FJP::SYMBOL_INT, FJP::SYMBOL_INT_ARRAY, FJP::SYMBOL_NOT_FOUND, FJP::Symbol::symbolType, FJP::TRUE, and FJP::Symbol::value.
processFor()
void FJP::Parser::processFor () private
Processes a 'for' loop (recursive descent).
Definition at line 1009 of file parser.cpp.
{
     // for
     if (token.tokenType != FJP::TokenType::FOR) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <assignment>
     token = lexer->getNextToken();
     processAssignment();
     // Store the start address of the condition of the for loop;
     int startCondition = generatedCode.getSize();
     // <condition>
     processCondition();
     // Generate a JPC instruction to skip the body of the for loop if the
     // condition is not satisfied. Also, create a JMP instruction in order to
     // skip the incrementation part of the for loop - we need to jump straight
     // to the body of the loop.
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, 0 });
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
     // Store the start address of the update part of the for loop (e.g. i++).
     int startUpdatePart = generatedCode.getSize();
     // ';'
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // <assignment>
     token = lexer->getNextToken();
     processAssignment(false);
     // After the second assignment (incrementation part), we need to jump back to the condition.
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, startCondition});
     // Store the address of the end of the incrementation part of the for loop.
     int endUpdatePart = generatedCode.getSize();
     // ')'
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // Once the body has been executed, jump straight to the update part (incrementation part).
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, startUpdatePart});
     // Set the address to jump to in case the condition isn't satisfied (end of the loop).
     generatedCode[startUpdatePart - 2].m = generatedCode.getSize();
     // Set the address to jump to after the condition has been processed (the body of the for loop).
     generatedCode[startUpdatePart - 1].m = endUpdatePart;
 }
References FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::exitProgramWithError(), FJP::FOR, FJP::JMP, FJP::JPC, FJP::LEFT_PARENTHESIS, FJP::RIGHT_PARENTHESIS, and FJP::SEMICOLON.
processForeach()
void FJP::Parser::processForeach () private
Processes a 'foreach' loop (recursive descent).
Definition at line 880 of file parser.cpp.
{
     // foreach
     if (token.tokenType != FJP::TokenType::FOREACH) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <identifier>
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_24, ERR_CODE, token.lineNumber);
     }
     // Make sure the identifier exists in the symbol table.
     FJP::Symbol iterVariable = symbolTable.findSymbol(token.value);
     if (iterVariable.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
     }
     // Make sure the identifier is one of the supported data types.
     switch (iterVariable.symbolType) {
         case FJP::SymbolType::SYMBOL_INT:
         case FJP::SymbolType::SYMBOL_BOOL:
             break;
         default:
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_32, ERR_CODE, token.lineNumber);
     }
     // ':'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::COLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_11, ERR_CODE, token.lineNumber);
     }
     // <identifier>
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_24, ERR_CODE, token.lineNumber);
     }
     // Make sure the identifier exists in the symbol table.
     FJP::Symbol dataArray = symbolTable.findSymbol(token.value);
     if (dataArray.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_09, ERR_CODE, token.lineNumber);
     }
     switch (iterVariable.symbolType) {
         // If the type of the iterator is an integer. The array has to be an array of integers.
         case FJP::SymbolType::SYMBOL_INT:
             if (dataArray.symbolType != FJP::SymbolType::SYMBOL_INT_ARRAY) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_42, ERR_CODE, token.lineNumber);
             }
             break;
         // If the type of the iterator is bool. The array has to be an array of booleans as well.
         case FJP::SymbolType::SYMBOL_BOOL:
             if (dataArray.symbolType != FJP::SymbolType::SYMBOL_BOOL_ARRAY) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_42, ERR_CODE, token.lineNumber);
             }
             break;
         default:
             break;
     }
     // ')'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     token = lexer->getNextToken();
     // Create a temporary "variable" on the stack that will be used to store
     // the current index as we iterate through the array.
     int indexAddress = nextFreeAddress;
     generatedCode.addInstruction({FJP::OP_CODE::INC, 0, 1});
     // Initialize the current index to 0 (the first element of the array).
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0});
     generatedCode.addInstruction({FJP::OP_CODE::STO, 0, indexAddress});
     // Start of the condition of the foreach loop (checking whether we've reached
     // the end of the array or not).
     int startForeachBody = generatedCode.getSize();
     // Check if we have just reached the end of the array (current index == array.size).
     generatedCode.addInstruction({FJP::OP_CODE::LOD, 0, indexAddress});
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, dataArray.size});
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ});
     // Skip the body of the foreach loop if the end of the array has been reached.
     int exitForeachAddress = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, 0});
     // Load array[index] to the top of the stack. We need to take the base address
     // of the array and add the current index to it, so we get the address of
     // the current element.
     generatedCode.addInstruction({FJP::OP_CODE::LOD, 0, indexAddress});
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, dataArray.address});
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
     generatedCode.addInstruction({FJP::OP_CODE::LDA, symbolTable.getDepthLevel() - dataArray.level, 0});
     // Store the value (array[index]) into the iterator.
     generatedCode.addInstruction({FJP::OP_CODE::STO, symbolTable.getDepthLevel() - iterVariable.level, iterVariable.address});
     // Increment the current index (moving on to the next element).
     generatedCode.addInstruction({FJP::OP_CODE::LOD, 0, indexAddress});
     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 1});
     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
     generatedCode.addInstruction({FJP::OP_CODE::STO, 0, indexAddress});
     // <statement>
     processStatement();
     // Jump to the incrementation part of the loop (index++).
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, startForeachBody});
     // Set the address to jump to in case the condition is not satisfied (end of the foreach loop).
     generatedCode[exitForeachAddress].m = generatedCode.getSize();
     // Remove the temporary variable (index) off the stack.
     generatedCode.addInstruction({FJP::OP_CODE::INC, 0, -1});
 }
References FJP::Symbol::address, FJP::COLON, FJP::CompilationErrors::ERROR_09, FJP::CompilationErrors::ERROR_11, FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_24, FJP::CompilationErrors::ERROR_32, FJP::CompilationErrors::ERROR_42, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::FOREACH, FJP::IDENTIFIER, FJP::INC, FJP::JMP, FJP::JPC, FJP::LDA, FJP::LEFT_PARENTHESIS, FJP::Symbol::level, FJP::LIT, FJP::LOD, FJP::OPR, FJP::OPR_NEQ, FJP::OPR_PLUS, FJP::RIGHT_PARENTHESIS, FJP::Symbol::size, FJP::STO, FJP::SYMBOL_BOOL, FJP::SYMBOL_BOOL_ARRAY, FJP::SYMBOL_INT, FJP::SYMBOL_INT_ARRAY, FJP::SYMBOL_NOT_FOUND, and FJP::Symbol::symbolType.
processFunction()
void FJP::Parser::processFunction () private
Processes a 'function' (recursive descent).
Definition at line 382 of file parser.cpp.
{
     std::string identifier;
     // function
     while (token.tokenType == FJP::TokenType::FUNCTION) {
         // <identifier>
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::IDENTIFIER) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_44, ERR_CODE, token.lineNumber);
         }
         // Make sure that the name of the identifier isn't already taken up.
         identifier = token.value;
         if (symbolTable.existsSymbol(identifier) ==  true) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_43, ERR_CODE, token.lineNumber);
         }
         // Add the symbol into the symbol table.
         symbolTable.addSymbol({FJP::SymbolType::SYMBOL_FUNCTION, token.value, generatedCode.getSize(), symbolTable.getDepthLevel(), nextFreeAddress, 0});
         // '('
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
         }
         // ')'
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
         }
         // '{'
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_18, ERR_CODE, token.lineNumber);
         }
         // Process the body of the function.
         token = lexer->getNextToken();
         processBlock();
         // '}'
         if (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_19, ERR_CODE, token.lineNumber);
         }
         // Load up the next token is it can be processed.
         token = lexer->getNextToken();
     }
 }
References FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_18, FJP::CompilationErrors::ERROR_19, FJP::CompilationErrors::ERROR_43, FJP::CompilationErrors::ERROR_44, FJP::exitProgramWithError(), FJP::FUNCTION, FJP::IDENTIFIER, FJP::LEFT_CURLY_BRACKET, FJP::LEFT_PARENTHESIS, FJP::RIGHT_CURLY_BRACKET, FJP::RIGHT_PARENTHESIS, and FJP::SYMBOL_FUNCTION.
processGoto()
void FJP::Parser::processGoto () private
Processes a 'goto' statement (recursive descent).
Definition at line 1212 of file parser.cpp.
{
     // goto
     if (token.tokenType != FJP::TokenType::GOTO) {
         return;
     }
     // <identifier>
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_24, ERR_CODE, token.lineNumber);
     }
     // Find the identifier in the symbol table.
     FJP::Symbol symbol = symbolTable.findSymbol(token.value);
     // If the identifier is not found, added it to the list
     // of labels that are still yet be declared (later on).
     // If the identifier is found, make sure its type is label.
     if (symbol.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         undefinedLabels[token.value].push_back(generatedCode.getSize());
     } else if (symbol.symbolType != FJP::SymbolType::SYMBOL_LABEL) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_33, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Added a JMP instruction to jump to the address of the label.
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, symbol.address});
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::Symbol::address, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_24, FJP::CompilationErrors::ERROR_33, FJP::exitProgramWithError(), FJP::GOTO, FJP::IDENTIFIER, FJP::JMP, FJP::SEMICOLON, FJP::SYMBOL_LABEL, FJP::SYMBOL_NOT_FOUND, and FJP::Symbol::symbolType.
processIf()
void FJP::Parser::processIf () private
Processes an 'if' statement (recursive descent).
Definition at line 665 of file parser.cpp.
{
     // 'if'
     if (token.tokenType != TokenType::IF) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <condition>
     token = lexer->getNextToken();
     processCondition();
     // Insert a JPC instruction (conditional jump).
     // If the result of the condition is false, we'll just skip the body of the if statement.
     int currentInstruction1 = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, 0});
     // ')'
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // else
     if (token.tokenType == FJP::TokenType::ELSE) {
         // Add a JMP instruction, so we can skip the else branch in case the condition is satisfied.
         int currentInstruction2 = generatedCode.getSize();
         generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
         // Set the address of the JPC instruction to jump to
         // in case the condition isn't satisfied - the else branch.
         generatedCode[currentInstruction1].m = generatedCode.getSize();
         // <statement>
         token = lexer->getNextToken();
         processStatement();
         // Set the address to jump to in case the condition is satisfied - skip the else branch.
         generatedCode[currentInstruction2].m = generatedCode.getSize();
     } else {
         // Set the address of the JPC instruction - skip the body of the if statement.
         generatedCode[currentInstruction1].m = generatedCode.getSize();
     }
 }
References FJP::ELSE, FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::exitProgramWithError(), FJP::IF, FJP::JMP, FJP::JPC, FJP::LEFT_PARENTHESIS, and FJP::RIGHT_PARENTHESIS.
processLabel()
void FJP::Parser::processLabel (const std::string label) private
Processes a 'label' (recursive descent).
Parameters
label name of the label (used in goto)
Definition at line 578 of file parser.cpp.
{
     // We don't have to check if the name is already taken as it was done above.
     symbolTable.addSymbol({FJP::SymbolType::SYMBOL_LABEL, label, 0, 0, generatedCode.getSize(), 0});
     // ':'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::COLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_11, ERR_CODE, token.lineNumber);
     }
     // If the label has been on the list of undefined labels (labels yet to be declared).
     // Change the jump address of the goto instruction and delete the label from the list.
     auto itr = undefinedLabels.find(label);
     if (itr != undefinedLabels.end()) {
         for (auto index : itr->second) {
             generatedCode[index].m = generatedCode.getSize();
         }
         undefinedLabels.erase(label);
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::COLON, FJP::CompilationErrors::ERROR_11, FJP::exitProgramWithError(), and FJP::SYMBOL_LABEL.
processRead()
void FJP::Parser::processRead () private
Processes a 'read' operation (recursive descent).
Definition at line 1578 of file parser.cpp.
{
     // 'read'
     if (token.tokenType != FJP::TokenType::READ) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <identifier>
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_44, ERR_CODE, token.lineNumber);
     }
     // Make sure that the identifier exists in the symbol table.
     FJP::Symbol symbol = symbolTable.findSymbol(token.value);
     if (symbol.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
     }
     // Check out the type of the identifier.
     switch (symbol.symbolType) {
         // int
         case FJP::SymbolType::SYMBOL_INT:
             generatedCode.addInstruction({FJP::OP_CODE::SIO, 0, FJP::SIO_TYPE::SIO_READ});
             generatedCode.addInstruction({FJP::OP_CODE::STO, symbolTable.getDepthLevel() - symbol.level, symbol.address});
             break;
         // bool
         case FJP::SymbolType::SYMBOL_BOOL:
             generatedCode.addInstruction({FJP::OP_CODE::SIO, 0, FJP::SIO_TYPE::SIO_READ});
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0 });
             // Convert an integer into a boolean (1/0).
             generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ });
             generatedCode.addInstruction({FJP::OP_CODE::STO, symbolTable.getDepthLevel() - symbol.level, symbol.address});
             break;
         // array
         case FJP::SymbolType::SYMBOL_INT_ARRAY:
         case FJP::SymbolType::SYMBOL_BOOL_ARRAY:
             // '['
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::LEFT_SQUARED_BRACKET) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_17, ERR_CODE, token.lineNumber);
             }
             // <expression>
             token = lexer->getNextToken();
             processExpression();
             // Calculate the address of the element (base + offset).
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.address });
             generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS });
             generatedCode.addInstruction({FJP::OP_CODE::SIO, 0, FJP::SIO_TYPE::SIO_READ});
             // If it is an array of booleans, interpret the numbers as booleans (1/0).
             if (symbol.symbolType == FJP::SymbolType::SYMBOL_BOOL_ARRAY) {
                 generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, 0 });
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_NEQ });
             }
             // ']'
             generatedCode.addInstruction({FJP::OP_CODE::STA, symbolTable.getDepthLevel() - symbol.level, 0});
             if (token.tokenType != FJP::TokenType::RIGHT_SQUARED_BRACKET) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_16, ERR_CODE, token.lineNumber);
             }
             break;
         default:
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_41, ERR_CODE, token.lineNumber);
             break;
     }
     // ')'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::Symbol::address, FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_16, FJP::CompilationErrors::ERROR_17, FJP::CompilationErrors::ERROR_41, FJP::CompilationErrors::ERROR_44, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::IDENTIFIER, FJP::LEFT_PARENTHESIS, FJP::LEFT_SQUARED_BRACKET, FJP::Symbol::level, FJP::LIT, FJP::OPR, FJP::OPR_NEQ, FJP::OPR_PLUS, FJP::READ, FJP::RIGHT_PARENTHESIS, FJP::RIGHT_SQUARED_BRACKET, FJP::SEMICOLON, FJP::SIO, FJP::SIO_READ, FJP::STA, FJP::STO, FJP::SYMBOL_BOOL, FJP::SYMBOL_BOOL_ARRAY, FJP::SYMBOL_INT, FJP::SYMBOL_INT_ARRAY, FJP::SYMBOL_NOT_FOUND, and FJP::Symbol::symbolType.
processRepeatUntil()
void FJP::Parser::processRepeatUntil () private
Processes a 'repeat-until' loop (recursive descent).
Definition at line 820 of file parser.cpp.
{
     // repeat
     if (token.tokenType != FJP::TokenType::REPEAT) {
         return;
     }
     // Start address of the body of the repeat-until loop.
     int repeatUntilStart = generatedCode.getSize();
     // '{'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_18, ERR_CODE, token.lineNumber);
     }
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // '}'
     if (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_19, ERR_CODE, token.lineNumber);
     }
     // until
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::UNTIL) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_39, ERR_CODE, token.lineNumber);
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <condition>
     token = lexer->getNextToken();
     processCondition();
     // If the result of condition is false (0) jump to the first address
     // of the body of the repeat-until loop.
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, repeatUntilStart });
     // ')'
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_18, FJP::CompilationErrors::ERROR_19, FJP::CompilationErrors::ERROR_39, FJP::exitProgramWithError(), FJP::JPC, FJP::LEFT_CURLY_BRACKET, FJP::LEFT_PARENTHESIS, FJP::REPEAT, FJP::RIGHT_CURLY_BRACKET, FJP::RIGHT_PARENTHESIS, FJP::SEMICOLON, and FJP::UNTIL.
processScope()
void FJP::Parser::processScope () private
Processes a 'scope' (recursive descent).
Definition at line 648 of file parser.cpp.
{
     // '{'
     if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
         return;
     }
     token = lexer->getNextToken();
     do {
         // Keep processing statements until you come across with a '}'
         processStatement();
     } while (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET);
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::LEFT_CURLY_BRACKET, and FJP::RIGHT_CURLY_BRACKET.
processStatement()
void FJP::Parser::processStatement () private
Processes a 'statement' (recursive descent).
Definition at line 434 of file parser.cpp.
{
     // ';' - nop
     if (token.tokenType == FJP::TokenType::SEMICOLON) {
         token = lexer->getNextToken();
         return;
     }
     processAssignment();
     processCall();
     processScope();
     processIf();
     processWhile();
     processDoWhile();
     processFor();
     processRepeatUntil();
     processForeach();
     processSwitch();
     processGoto();
     processRead();
     processWrite();
 }
References FJP::SEMICOLON.
processSwitch()
void FJP::Parser::processSwitch () private
Processes a 'switch' statement (recursive descent).
Definition at line 1076 of file parser.cpp.
{
     // List of the address of break statements that will need to be set
     // once the end address is known (the end of the switch statement).
     std::list<int> breaks;
     // switch
     if (token.tokenType != FJP::TokenType::SWITCH) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <identifier>
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::IDENTIFIER) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_44, ERR_CODE, token.lineNumber);
     }
     // Make sure the identifier exists in the symbol table.
     Symbol variable = symbolTable.findSymbol(token.value);
     if (variable.symbolType == FJP::SYMBOL_NOT_FOUND) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
     }
     // ')'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // '{'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_18, ERR_CODE, token.lineNumber);
     }
     // <cases>
     token = lexer->getNextToken();
     processCases(variable, breaks);
     // '}'
     if (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_19, ERR_CODE, token.lineNumber);
     }
     // Set the jump address of all the break statements. The jumps address
     // is the end of the switch statement.
     for (const auto &item : breaks) {
         generatedCode[item].m = generatedCode.getSize();
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_18, FJP::CompilationErrors::ERROR_19, FJP::CompilationErrors::ERROR_44, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::IDENTIFIER, FJP::LEFT_CURLY_BRACKET, FJP::LEFT_PARENTHESIS, FJP::RIGHT_CURLY_BRACKET, FJP::RIGHT_PARENTHESIS, FJP::SWITCH, FJP::SYMBOL_NOT_FOUND, and FJP::Symbol::symbolType.
processTerm()
void FJP::Parser::processTerm () private
Processes a 'term' (recursive descent).
Definition at line 1431 of file parser.cpp.
{
     FJP::TokenType currTokenType;
     // <factor>
     processFactor();
     // * /
     while (token.tokenType == FJP::TokenType::ASTERISK || token.tokenType == FJP::TokenType::SLASH) {
         currTokenType = token.tokenType;
         // <factor>
         token = lexer->getNextToken();
         processFactor();
         // Add instruction to perform the operation on the top of the stack.
         switch (currTokenType) {
             // '*'
             case FJP::TokenType::ASTERISK:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_MUL});
                 break;
             // '/'
             case FJP::TokenType::SLASH:
                 generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_DIV});
                 break;
             default:
                 break;
         }
     }
 }
References FJP::ASTERISK, FJP::OPR, FJP::OPR_DIV, FJP::OPR_MUL, and FJP::SLASH.
processTernaryOperator()
void FJP::Parser::processTernaryOperator () private
Processes a 'ternary operator' (recursive descent).
Definition at line 1342 of file parser.cpp.
{
     // <condition>
     token = lexer->getNextToken();
     processCondition();
     // '?'
     if (token.tokenType != FJP::TokenType::QUESTION_MARK) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_20, ERR_CODE, token.lineNumber);
     }
     // Add JMP instructions, so we can jump to the appropriate
     // expression based on the result of the condition.
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, generatedCode.getSize() + 2});
     int jmpInstructionAddress = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
     int jmp2InstructionAddress = generatedCode.getSize();
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, 0});
     // <expression>
     token = lexer->getNextToken();
     processExpression();
     // ':'
     if (token.tokenType != FJP::TokenType::COLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_11, ERR_CODE, token.lineNumber);
     }
     // Set the address of the first expression (it's now known since it's been parsed).
     generatedCode[jmpInstructionAddress].m = generatedCode.getSize();
     // <expression>
     token = lexer->getNextToken();
     processExpression();
     // Set the address of the second expression (it's now known since it's been parsed).
     generatedCode[jmp2InstructionAddress].m = generatedCode.getSize();
 }
References FJP::COLON, FJP::CompilationErrors::ERROR_11, FJP::CompilationErrors::ERROR_20, FJP::exitProgramWithError(), FJP::JMP, FJP::JPC, and FJP::QUESTION_MARK.
processVariable()
void FJP::Parser::processVariable (int & frameVariableCount) private
Processes a 'variable' (recursive descent).
Definition at line 215 of file parser.cpp.
{
     // int/bool
     FJP::TokenType dataType = token.tokenType;
     if (!(dataType == FJP::TokenType::INT || dataType == FJP::TokenType::BOOL)) {
         return;
     }
     int arrayAddress;  // start address of an array
     int arraySize = 0; // size of an array
     int arrayDepth;    // level/depth of an array
     int number;
     std::string identifier;
     FJP::Symbol symbol;
     while (true) {
         // identifier
         token = lexer->getNextToken();
         if (token.tokenType != FJP::TokenType::IDENTIFIER) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_04, ERR_CODE, token.lineNumber);
         }
         // Make sure the name is not already taken.
         identifier = token.value;
         if (symbolTable.existsSymbol(identifier) ==  true) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_43, ERR_CODE, token.lineNumber);
         }
         switch (dataType) {
             // int (default value is 0)
             case FJP::TokenType::INT:
                 symbolTable.addSymbol({FJP::SymbolType::SYMBOL_INT, identifier, DEFAULT_INT_VALUE, symbolTable.getDepthLevel(), nextFreeAddress, 0 });
                 break;
             // bool (default value is false)
             case FJP::TokenType::BOOL:
                 symbolTable.addSymbol({FJP::SymbolType::SYMBOL_BOOL, identifier, DEFAULT_BOOL_VALUE, symbolTable.getDepthLevel(), nextFreeAddress, 0 });
                 break;
             default:
                 break;
         }
         nextFreeAddress++;
         frameVariableCount++;
         // Store the level of the variable in case it is an array - it will need to be
         // escalated from an ordinary integer/bool.
         arrayDepth = symbolTable.getDepthLevel();
         // '['
         token = lexer->getNextToken();
         if (token.tokenType == FJP::TokenType::LEFT_SQUARED_BRACKET) {
             arrayAddress = nextFreeAddress - 1;
             token = lexer->getNextToken();
             switch (token.tokenType) {
                 // number e.g. arr[10]
                 case FJP::TokenType::NUMBER:
                     arraySize = atoi(token.value.c_str());
                     if (arraySize <= 0) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_40, ERR_CODE, token.lineNumber);
                     }
                     nextFreeAddress += (arraySize - 1); // -1 because the int is already there, it has just been escalated to an array
                     frameVariableCount += (arraySize - 1);
                     symbolTable.makeArray(identifier, arraySize);
                     break;
                 // identifier  e.g. arr[N]
                 case FJP::TokenType::IDENTIFIER:
                     // Make sure the symbol does exist in the symbol table.
                     symbol = symbolTable.findSymbol(token.value);
                     if (symbol.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
                     }
                     // An array can be initialized only with a constance value.
                     if (symbol.symbolType != FJP::SymbolType::SYMBOL_CONST) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_06, ERR_CODE, token.lineNumber);
                     }
                     // Arrays of a size less than 1 are not allowed.
                     if (symbol.value < 1) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_40, ERR_CODE, token.lineNumber);
                     }
                     nextFreeAddress += (symbol.value - 1);
                     frameVariableCount += (symbol.value - 1);
                     symbolTable.makeArray(identifier, symbol.value);
                     arraySize = symbol.value;
                     break;
                 default:
                     FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_26, ERR_CODE, token.lineNumber);
                     break;
             }
             // ']'
             token = lexer->getNextToken();
             if (token.tokenType != FJP::TokenType::RIGHT_SQUARED_BRACKET) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_16, ERR_CODE, token.lineNumber);
             }
             token = lexer->getNextToken();
             // '='
             if (token.tokenType == FJP::TokenType::CONST_INIT) {
                 // '{'
                 token = lexer->getNextToken();
                 if (token.tokenType != FJP::TokenType::LEFT_CURLY_BRACKET) {
                     FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_18, ERR_CODE, token.lineNumber);
                 }
                 // If the user decides to initialize the array, they need
                 // to initialize all elements, not just a subarray.
                 for (int i = 0; i < arraySize; i++) {
                     token = lexer->getNextToken();
                     switch (dataType) {
                         // 'int'
                         case FJP::TokenType::INT:
                             if (token.tokenType != FJP::TokenType::NUMBER) {
                                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_07, ERR_CODE, token.lineNumber);
                             }
                             number = atoi(token.value.c_str());
                             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, number});
                             generatedCode.addInstruction({FJP::OP_CODE::STO, symbolTable.getDepthLevel() - arrayDepth, arrayAddress + i});
                             break;
                         // 'bool'
                         case FJP::TokenType::BOOL:
                             // If it's an array of booleans, the only allowed values are true and false.
                             if (!(token.tokenType == FJP::TokenType::TRUE || token.tokenType == FJP::TokenType::FALSE)) {
                                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_10, ERR_CODE, token.lineNumber);
                             }
                             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, token.tokenType == FJP::TokenType::TRUE});
                             generatedCode.addInstruction({FJP::OP_CODE::STO, symbolTable.getDepthLevel() - arrayDepth, arrayAddress + i});
                             break;
                         default:
                             break;
                     }
                     // Make sure the whole array has been initialized.
                     token = lexer->getNextToken();
                     if (token.tokenType != FJP::TokenType::COMMA && i < arraySize - 1) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_08, ERR_CODE, token.lineNumber);
                     }
                 }
                 // '}'
                 if (token.tokenType != FJP::TokenType::RIGHT_CURLY_BRACKET) {
                     FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_19, ERR_CODE, token.lineNumber);
                 }
                 token = lexer->getNextToken();
             }
         }
         // ','
         if (token.tokenType != FJP::TokenType::COMMA) {
             break;
         }
     }
     // ';'
     if (token.tokenType !=  FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
         return;
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
     // Recursively call the same function in case there are more lines of variable declarations.
     processVariable(frameVariableCount);
 }
References FJP::BOOL, FJP::COMMA, FJP::CONST_INIT, FJP::CompilationErrors::ERROR_04, FJP::CompilationErrors::ERROR_06, FJP::CompilationErrors::ERROR_07, FJP::CompilationErrors::ERROR_08, FJP::CompilationErrors::ERROR_10, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_16, FJP::CompilationErrors::ERROR_18, FJP::CompilationErrors::ERROR_19, FJP::CompilationErrors::ERROR_26, FJP::CompilationErrors::ERROR_40, FJP::CompilationErrors::ERROR_43, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::FALSE, FJP::IDENTIFIER, FJP::INT, FJP::LEFT_CURLY_BRACKET, FJP::LEFT_SQUARED_BRACKET, FJP::LIT, FJP::NUMBER, FJP::RIGHT_CURLY_BRACKET, FJP::RIGHT_SQUARED_BRACKET, FJP::SEMICOLON, FJP::STO, FJP::SYMBOL_BOOL, FJP::SYMBOL_CONST, FJP::SYMBOL_INT, FJP::SYMBOL_NOT_FOUND, FJP::Symbol::symbolType, FJP::TRUE, and FJP::Symbol::value.
processWhile()
void FJP::Parser::processWhile () private
Processes a 'while' loop (recursive descent).
Definition at line 718 of file parser.cpp.
{
     // while
     if (token.tokenType != FJP::TokenType::WHILE) {
         return;
     }
     // Start address of the while loop.
     int startWhileLoop = generatedCode.getSize();
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     // <condition>
     token = lexer->getNextToken();
     processCondition();
     int endOfWhileCondition = generatedCode.getSize();
     // ')'
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // Add a JPC instruction (conditional jump) in order to skip the body of the
     // while loop in case the condition is not satisfied.
     generatedCode.addInstruction({FJP::OP_CODE::JPC, 0, 0 });
     // <statement>
     token = lexer->getNextToken();
     processStatement();
     // Jump back to the condition of the while loop.
     generatedCode.addInstruction({FJP::OP_CODE::JMP, 0, startWhileLoop});
     // Set the target jump address of the JPC instruction (in order to skip the body of the loop).
     generatedCode[endOfWhileCondition].m = generatedCode.getSize();
 }
References FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::exitProgramWithError(), FJP::JMP, FJP::JPC, FJP::LEFT_PARENTHESIS, FJP::RIGHT_PARENTHESIS, and FJP::WHILE.
processWrite()
void FJP::Parser::processWrite () private
Processes a 'write' operation (recursive descent).
Definition at line 1668 of file parser.cpp.
{
     // 'write'
     if (token.tokenType != FJP::TokenType::WRITE) {
         return;
     }
     // '('
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::LEFT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_12, ERR_CODE, token.lineNumber);
     }
     int number;
     FJP::Symbol symbol;
     token = lexer->getNextToken();
     switch (token.tokenType) {
         // <identifier>
         case FJP::TokenType::IDENTIFIER:
             // Make sure that the identifier has been declared (exists in the symbol table).
             symbol = symbolTable.findSymbol(token.value);
             if (symbol.symbolType == FJP::SymbolType::SYMBOL_NOT_FOUND) {
                 FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_45, ERR_CODE, token.lineNumber);
             }
             // Check out the type of the identifier.
             switch (symbol.symbolType) {
                 // <int/bool>
                 case FJP::SymbolType::SYMBOL_INT:
                 case FJP::SymbolType::SYMBOL_BOOL:
                     generatedCode.addInstruction({FJP::OP_CODE::LOD, symbolTable.getDepthLevel() - symbol.level, symbol.address});
                     break;
                 // <int[]/bool[]>
                 case FJP::SymbolType::SYMBOL_INT_ARRAY:
                 case FJP::SymbolType::SYMBOL_BOOL_ARRAY:
                     // '['
                     token = lexer->getNextToken();
                     if (token.tokenType != FJP::TokenType::LEFT_SQUARED_BRACKET) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_17, ERR_CODE, token.lineNumber);
                     }
                     // <expression>
                     token = lexer->getNextToken();
                     processExpression();
                     // Calculate the address of the element (base + offset).
                     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.address});
                     generatedCode.addInstruction({FJP::OP_CODE::OPR, 0, FJP::OPRType::OPR_PLUS});
                     generatedCode.addInstruction({FJP::OP_CODE::LDA, symbolTable.getDepthLevel() - symbol.level, 0});
                     // ']'
                     if (token.tokenType != FJP::TokenType::RIGHT_SQUARED_BRACKET) {
                         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_16, ERR_CODE, token.lineNumber);
                     }
                     break;
                 // <const>
                 case FJP::SymbolType::SYMBOL_CONST:
                     generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, symbol.value});
                     break;
                 default:
                     FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_41, ERR_CODE, token.lineNumber);
                     break;
             }
             break;
         // <number>
         case FJP::TokenType::NUMBER:
             number = atoi(token.value.c_str());
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, number});
             break;
         // <true/false>
         case FJP::TokenType::TRUE:
         case FJP::TokenType::FALSE:
             generatedCode.addInstruction({FJP::OP_CODE::LIT, 0, token.tokenType == FJP::TokenType::TRUE});
             break;
         default:
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_30, ERR_CODE, token.lineNumber);
             break;
     }
     // Print off the value from the top of the stack.
     generatedCode.addInstruction({FJP::OP_CODE::SIO, 0, FJP::SIO_TYPE::SIO_WRITE});
     // ')'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::RIGHT_PARENTHESIS) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_13, ERR_CODE, token.lineNumber);
     }
     // ';'
     token = lexer->getNextToken();
     if (token.tokenType != FJP::TokenType::SEMICOLON) {
         FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_15, ERR_CODE, token.lineNumber);
     }
     // Load up the next token, so it can be processed.
     token = lexer->getNextToken();
 }
References FJP::Symbol::address, FJP::CompilationErrors::ERROR_12, FJP::CompilationErrors::ERROR_13, FJP::CompilationErrors::ERROR_15, FJP::CompilationErrors::ERROR_16, FJP::CompilationErrors::ERROR_17, FJP::CompilationErrors::ERROR_30, FJP::CompilationErrors::ERROR_41, FJP::CompilationErrors::ERROR_45, FJP::exitProgramWithError(), FJP::FALSE, FJP::IDENTIFIER, FJP::LDA, FJP::LEFT_PARENTHESIS, FJP::LEFT_SQUARED_BRACKET, FJP::Symbol::level, FJP::LIT, FJP::LOD, FJP::NUMBER, FJP::OPR, FJP::OPR_PLUS, FJP::RIGHT_PARENTHESIS, FJP::RIGHT_SQUARED_BRACKET, FJP::SEMICOLON, FJP::SIO, FJP::SIO_WRITE, FJP::SYMBOL_BOOL, FJP::SYMBOL_BOOL_ARRAY, FJP::SYMBOL_CONST, FJP::SYMBOL_INT, FJP::SYMBOL_INT_ARRAY, FJP::SYMBOL_NOT_FOUND, FJP::Symbol::symbolType, FJP::TRUE, FJP::Symbol::value, and FJP::WRITE.
storeCodeInstructionsIntoFile()
void FJP::Parser::storeCodeInstructionsIntoFile () private
Stores the instructions of the output code into a file.
Definition at line 67 of file parser.cpp.
{
     // Open up the output file.
     std::ofstream file = std::ofstream (std::string(OUTPUT_FILE));
     // Make sure the file has been successfully opened.
     if (file.is_open() == false) {
         FJP::exitProgramWithError(FJP::IOErrors::ERROR_01, ERR_CODE);
         return;
     }
     // Store the generated code into the file.
     for (int i = 0; i < generatedCode.getSize(); i++) {
         file
              #ifdef  PRINT_ADDRESSES
                 << "[#" << std::setw(ADDRESS_LEN) << std::setfill('0') << i << "] "
              #endif
              << generatedCode[i];
         if (i < generatedCode.getSize() - 1) {
             file << "\n";
         }
     }
     // Close the file at the end.
     file.close();
 }
References FJP::IOErrors::ERROR_01, and FJP::exitProgramWithError().
Member Data Documentation
ADDRESS_LEN
constexpr int FJP::Parser::ADDRESS_LEN = 3 static constexpr private
Number of digits an address is aligned to when being printed out.
Definition at line 30 of file parser.h.
DEFAULT_BOOL_VALUE
constexpr int FJP::Parser::DEFAULT_BOOL_VALUE = 0 static constexpr private
Default value of a bool variable (false).
Definition at line 21 of file parser.h.
DEFAULT_INT_VALUE
constexpr int FJP::Parser::DEFAULT_INT_VALUE = 0 static constexpr private
Default value of an integer variable.
Definition at line 18 of file parser.h.
ERR_CODE
constexpr int FJP::Parser::ERR_CODE = 2 static constexpr private
Parser error code (used when terminating the application).
Definition at line 24 of file parser.h.
FRAME_INIT_VAR_COUNT
constexpr int FJP::Parser::FRAME_INIT_VAR_COUNT = 4 static constexpr private
Number of variables stored onto the stack upon a function call.
Definition at line 33 of file parser.h.
generatedCode
FJP::GeneratedCode FJP::Parser::generatedCode private
Output of the parser - generated code.
Definition at line 43 of file parser.h.
instance
FJP::Parser * FJP::Parser::instance = nullptr static private
The instance of the class.
Definition at line 37 of file parser.h.
Referenced by getInstance().
lastProcessVariable
FJP::Symbol FJP::Parser::lastProcessVariable private
Last processed variable - used in multi assignment.
Definition at line 60 of file parser.h.
lexer
FJP::ILexer* FJP::Parser::lexer private
An instance of Lexer (set upon initialization).
Definition at line 40 of file parser.h.
nextFreeAddress
int FJP::Parser::nextFreeAddress private
Next free address within one function call.
This address is used to store variables/arrays.
Definition at line 53 of file parser.h.
OUTPUT_FILE
constexpr const char* FJP::Parser::OUTPUT_FILE = "code.pl0" static constexpr private
Output file containing the stack trace as the program is being executed.
Definition at line 27 of file parser.h.
symbolTable
FJP::SymbolTable FJP::Parser::symbolTable private
Symbol table used during the recursive descent algorithm.
Definition at line 46 of file parser.h.
token
FJP::Token FJP::Parser::token private
Current token retrieved from the lexer.
Definition at line 49 of file parser.h.
undefinedLabels
std::map<std::string, std::list<int> > FJP::Parser::undefinedLabels private
Associative array of labels that need to be defined.
Their address is not yet known.
Definition at line 57 of file parser.h.
The documentation for this class was generated from the following files:
include/parser.h
src/parser.cpp