KIV/FJP Compiler: FJP::VirtualMachine Class Reference
FJP::VirtualMachine Class Reference
Virtual machine used to execute the code generated by the parser.
#include <vm.h>
Public Member Functions
void execute (FJP::GeneratedCode &program, bool debug=false) override
Executes a program given as a parameter.
Static Public Member Functions
static VirtualMachine * getInstance ()
Returns the instance of the VirtualMachine class.
Private Member Functions
VirtualMachine ()
Constructor - creates an instance of the class.
VirtualMachine (VirtualMachine &)=delete
Deleted copy constructor of the class.
void operator= (VirtualMachine const &)=delete
Deleted assign operator of the class.
void init ()
Initializes the virtual machine - sets the registers, clears out the stack, and so on.
void fetch ()
Fetches the next instruction to be executed.
void execute ()
Executes the current instruction.
int base (int l, int base)
Calculates the address where a variable is actually stored within the stack (it might be stored in a different frame/depth/level)
void execute_LIT (int l, int m)
Executes the LIT instruction.
void execute_OPR (int l, int m)
Executes the OPR instruction.
void execute_LOD (int l, int m)
Executes the LOD instruction.
void execute_STO (int l, int m)
Executes the STO instruction.
void execute_CAL (int l, int m)
Executes the CAL instruction.
void execute_INC (int l, int m)
Executes the INC instruction.
void execute_JMP (int l, int m)
Executes the JMP instruction.
void execute_JPC (int l, int m)
Executes the JPC instruction.
void execute_SIO (int l, int m)
Executes the SIO instruction.
void execute_LDA (int l, int m)
Executes the LDA instruction.
void execute_STA (int l, int m)
Executes the STA instruction.
void execute_DEC (int l, int m)
Executes the DEC instruction.
bool checkIfOverflows (std::function< int(int, int)> operation, int x, int y)
Checks if the operation would cause an overflow exception.
Private Attributes
int stackMemory [STACK_SIZE]
internal stack used to perform operations as defined in the program
int returnAddresses [STACK_SIZE]
list of return addresses
int returnAddressCount
number of return addresses stored in the list
int ESP
stack pointer
int EBP
base pointer
int EIP
instruction pointer
int halt
flag indicating the end of the program
bool debug
flag pass in from the main function - create the stack trace output file or not
FJP::Instruction instruction
current instruction
FJP::GeneratedCode * program
program to be executed (input data of the virtual machine)
std::ofstream outputFile
output file (stream) - stack trace
Static Private Attributes
static constexpr int STACK_SIZE = 1024
size of the virtual stack (1 KB)
static constexpr int ERROR_CODE = 3
error code of the VM (runtime exception)
static constexpr const char * OUTPUT_FILE = "stacktrace.txt"
name of the output file
static VirtualMachine * instance = nullptr
the instance of the VirtualMachine class
Detailed Description
Virtual machine used to execute the code generated by the parser.
It internally creates a virtual stack in order to be able to perform all the operations. Also, if enabled, it generates an output file containing stack trace information of the program as it is being executed.
Definition at line 16 of file vm.h.
Constructor & Destructor Documentation
VirtualMachine() [1/2]
FJP::VirtualMachine::VirtualMachine () private
Constructor - creates an instance of the class.
Definition at line 16 of file vm.cpp.
{
 }
Referenced by getInstance().
VirtualMachine() [2/2]
FJP::VirtualMachine::VirtualMachine (VirtualMachine &) private delete
Deleted copy constructor of the class.
Member Function Documentation
base()
int FJP::VirtualMachine::base (int l, int base) private
Calculates the address where a variable is actually stored within the stack (it might be stored in a different frame/depth/level)
Definition at line 133 of file vm.cpp.
{
     // Return the base pointer of the frame
     // 'levels' above (down the stack)
     while (l > 0) {
         base = stackMemory[base + 1];
         l--;
     }
     return base;
 }
checkIfOverflows()
bool FJP::VirtualMachine::checkIfOverflows (std::function< int(int, int)> operation, int x, int y) private
Checks if the operation would cause an overflow exception.
Parameters
operation the operation to be performed on the x and y parameters
x first parameter of the operation
y second parameter of the operation
Returns
true/false depending on whether the operation would cause an overflow exception
Definition at line 143 of file vm.cpp.
{
     // Performs the operation.
     int result = operation(x, y);
     // Check if an overflow error has occurred.
     return (x < 0 && y < 0 && result > 0) || (x > 0 && y > 0 && result < 0);
 }
execute() [1/2]
void FJP::VirtualMachine::execute () private
Executes the current instruction.
Definition at line 72 of file vm.cpp.
{
     if (debug) {
         // If debug is enabled, print out the current
         // instruction that is about to be executed.
         outputFile << (EIP - 1) << "\t" << op_code_to_str(instruction.op) << "\t" << instruction.l << "\t" << instruction.m << "\t";
     }
     // Execute the current instruction
     switch (instruction.op) {
         case LIT:
             execute_LIT(instruction.l, instruction.m);
             break;
         case OPR:
             execute_OPR(instruction.l, instruction.m);
             break;
         case LOD:
             execute_LOD(instruction.l, instruction.m);
             break;
         case STO:
             execute_STO(instruction.l, instruction.m);
             break;
         case CAL:
             execute_CAL(instruction.l, instruction.m);
             break;
         case INC:
             execute_INC(instruction.l, instruction.m);
             break;
         case JMP:
             execute_JMP(instruction.l, instruction.m);
             break;
         case JPC:
             execute_JPC(instruction.l, instruction.m);
             break;
         case SIO:
             execute_SIO(instruction.l, instruction.m);
             break;
         case LDA:
             execute_LDA(instruction.l, instruction.m);
             break;
         case STA:
             execute_STA(instruction.l, instruction.m);
             break;
     }
     if (debug) {
         // Print out the current values of all three registers.
         outputFile << EIP << "\t" << EBP << "\t" << ESP << "\t";
         // Print out the content of the stack. The frames
         // are separated by the '|' symbol
         int index = 0;
         for (int i = 1; i <= ESP; i++) {
             if (index < returnAddressCount && returnAddresses[index] < i) {
                 outputFile << "| ";
                 index++;
             }
             outputFile << stackMemory[i] << " ";
         }
         outputFile << "\n";
     }
 }
References FJP::CAL, FJP::INC, FJP::JMP, FJP::JPC, FJP::LDA, FJP::LIT, FJP::LOD, FJP::op_code_to_str(), FJP::OPR, FJP::SIO, FJP::STA, and FJP::STO.
execute() [2/2]
void FJP::VirtualMachine::execute (FJP::GeneratedCode & program, bool debug = false) override virtual
Executes a program given as a parameter.
Parameters
program the instance of a program to be executed
debug flag if want to create an output file - stacktrace.txt
Implements FJP::IVM.
Definition at line 19 of file vm.cpp.
{
     // Store the parameters.
     this->debug = debug;
     this->program = &program;
     // Init the virtual machine.
     init();
     // If debug is enabled, open up the output file.
     if (debug) {
         outputFile = std::ofstream(OUTPUT_FILE);
         if (outputFile.is_open() == false) {
             FJP::exitProgramWithError(FJP::IOErrors::ERROR_01, ERROR_CODE);
         }
         // This is the header of the file.
         outputFile << "\t\t\t\tEIP\tEBP\tESP\tstack\n";
         outputFile << "initial values\t\t\t" << EIP << "\t" << EBP << "\t" << ESP << '\n';
     }
     // Executes the program. Keep fetching and executing
     // instructions until the vm gets halted.
     while (halt == 1 && EBP != 0) {
         fetch();
         execute();
     }
     // Close up the output file if debug is enabled.
     if (outputFile.is_open() == true) {
         outputFile.close();
     }
 }
References FJP::IOErrors::ERROR_01, and FJP::exitProgramWithError().
execute_CAL()
void FJP::VirtualMachine::execute_CAL (int l, int m) private
Executes the CAL instruction.
The CAL instruction calls a function stored at its assigned address
Parameters
l depth/level of the function
m address of the function
Definition at line 270 of file vm.cpp.
{
     // Push all necessary values on the stack
     // before jumping to the first address of the function.
     stackMemory[ESP + 1] = 0;
     stackMemory[ESP + 2] = base(l, EBP);
     stackMemory[ESP + 3] = EBP;
     stackMemory[ESP + 4] = EIP;
     // Set the new base pointer.
     EBP = ESP + 1;
     // Set the instruction pointer to the
     // first address of the function.
     EIP = m;
     // Store the return address.
     returnAddresses[returnAddressCount] = ESP;
     returnAddressCount++;
 }
execute_DEC()
void FJP::VirtualMachine::execute_DEC (int l, int m) private
Executes the DEC instruction.
The DEC instruction does the opposite to the INC instruction. It decrements the ESP register by a value passed in the m parameter.
Parameters
l unused
m the value by which we want to decrement the stack pointer
execute_INC()
void FJP::VirtualMachine::execute_INC (int l, int m) private
Executes the INC instruction.
The INC instruction allocates some space on the stack. It's done by adding a certain number to the stack pointer, e.g. +12 allocates 12 positions (slots) on the stack.
Parameters
l unused
m number by which the stack pointer will be increased
Definition at line 290 of file vm.cpp.
{
     // Just so the compiler doesn't complain about an unused value.
     (void)l;
     // Make sure that there is enough free space on the stack.
     if (m + ESP > STACK_SIZE) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Allocate 'm' spots on the stack.
     ESP = ESP + m;
 }
References FJP::RuntimeErrors::ERROR_00, and FJP::exitProgramWithError().
execute_JMP()
void FJP::VirtualMachine::execute_JMP (int l, int m) private
Executes the JMP instruction.
The JPM instruction does nothing but jumps to a specific address
Parameters
l unused
m the target address to jump to
Definition at line 303 of file vm.cpp.
{
     // Just so the compiler doesn't complain about an unused value.
     (void)l;
     // Set the value of the instruction pointer.
     EIP = m;
 }
execute_JPC()
void FJP::VirtualMachine::execute_JPC (int l, int m) private
Executes the JPC instruction.
The JPC instruction represents a conditional jump based on the value stored on the top of the stack. It jumps to a given address if there is 1 on the top of the stack.
Parameters
l level/depth of th target address
m target address
Definition at line 311 of file vm.cpp.
{
     (void)l;
     if (stackMemory[ESP] == 0) {
         EIP = m;
     }
     ESP--;
 }
execute_LDA()
void FJP::VirtualMachine::execute_LDA (int l, int m) private
Executes the LDA instruction.
The LDA instruction loads a value from a certain address and pushes it onto the stack. The instruction expects the address to be stored on the top of the stack beforehand.
Parameters
l level/depth of the source address
m unused
Definition at line 319 of file vm.cpp.
{
     // Just so the compiler doesn't complain about an unused value.
     (void)m;
     // Calculate the address within the corresponding frame.
     int frameAddress = base(l, EBP) + stackMemory[ESP];
     // Make sure the source address exists within the stack.
     if (frameAddress > ESP || frameAddress < 0) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Load the value up from the address to the top of the stack.
     stackMemory[ESP] = stackMemory[frameAddress];
 }
References FJP::RuntimeErrors::ERROR_00, and FJP::exitProgramWithError().
execute_LIT()
void FJP::VirtualMachine::execute_LIT (int l, int m) private
Executes the LIT instruction.
The LIT instruction pushes a constant value on the top of the stack
Parameters
l unused
m the constant to be pushed onto the stack
Definition at line 151 of file vm.cpp.
{
     // So the compiler doesn't complain about an unused variable.
     (void)l;
     // Make sure that the stack is not all taken up
     if (ESP == STACK_SIZE) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Push the 'm' value on the top of the stack.
     ESP++;
     stackMemory[ESP] = m;
 }
References FJP::RuntimeErrors::ERROR_00, and FJP::exitProgramWithError().
execute_LOD()
void FJP::VirtualMachine::execute_LOD (int l, int m) private
Executes the LOD instruction.
The LOD instruction loads a value from a certain address to the top of the stack.
Parameters
l depth/level of the symbol (address)
m address of the symbol
Definition at line 253 of file vm.cpp.
{
     // Make sure that the stack is not all taken up
     if (ESP == STACK_SIZE) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Load the value from the address to the top of the stack.
     ESP++;
     stackMemory[ESP] = stackMemory[base(l, EBP) + m];
 }
References FJP::RuntimeErrors::ERROR_00, and FJP::exitProgramWithError().
execute_OPR()
void FJP::VirtualMachine::execute_OPR (int l, int m) private
Executes the OPR instruction.
The OPR instruction can perform the following operations: m = 0 -> return m = 1 -> x = -x m = 2 -> x + y m = 3 -> x - y m = 4 -> x * y m = 5 -> x / y m = 6 -> x % 2 m = 7 -> x % y m = 8 -> x == y m = 9 -> x != y m = 10 -> x < y m = 11 -> x <= y m = 12 -> x > y m = 12 -> x >= y
Parameters
l unused
m type of the operations
Definition at line 165 of file vm.cpp.
{
     // So the compiler doesn't complain about an unused variable.
     (void)l;
     // Perform the corresponding operation.
     switch (m) {
         // return
         case FJP::OPRType::OPR_RET:
             ESP = EBP - 1;
             EIP = stackMemory[ESP + 4];
             EBP = stackMemory[ESP + 3];
             returnAddressCount--;
             break;
         // x = -x
         case FJP::OPRType::OPR_INVERT_VALUE:
             stackMemory[ESP] = -1 * stackMemory[ESP];
             break;
         // x + y
         case FJP::OPRType::OPR_PLUS:
             ESP--;
             if (checkIfOverflows([&](int x, int y) {return x + y; }, stackMemory[ESP], stackMemory[ESP + 1])) {
                 FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_02, ERROR_CODE);
             }
             stackMemory[ESP] = stackMemory[ESP] + stackMemory[ESP + 1];
             break;
         // x - y
         case FJP::OPRType::OPR_MINUS:
             ESP--;
             stackMemory[ESP] = stackMemory[ESP] - stackMemory[ESP + 1];
             break;
         // x * y
         case OPR_MUL:
             ESP--;
             if (checkIfOverflows([&](int x, int y) {return x * y; }, stackMemory[ESP], stackMemory[ESP + 1])) {
                 FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_02, ERROR_CODE);
             }
             stackMemory[ESP] = stackMemory[ESP] * stackMemory[ESP + 1];
             break;
         // x / y
         case FJP::OPRType::OPR_DIV:
             ESP--;
             if (stackMemory[ESP + 1] == 0) {
                 FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_01, ERROR_CODE);
             }
             stackMemory[ESP] = stackMemory[ESP] / stackMemory[ESP + 1];
             break;
         // x % 2
         case FJP::OPRType::OPR_ODD:
             stackMemory[ESP] = stackMemory[ESP] % 2;
             break;
         // x % y
         case FJP::OPRType::OPR_MOD:
             ESP--;
             stackMemory[ESP] = stackMemory[ESP] % stackMemory[ESP + 1];
             break;
         // x == y
         case FJP::OPRType::OPR_EQ:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] == stackMemory[ESP + 1]);
             break;
         // x != y
         case FJP::OPRType::OPR_NEQ:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] != stackMemory[ESP + 1]);
             break;
         // x < y
         case OPR_LESS:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] < stackMemory[ESP + 1]);
             break;
         // x <= y
         case FJP::OPRType::OPR_LESS_EQ:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] <= stackMemory[ESP + 1]);
             break;
         // x > y
         case FJP::OPRType::OPR_GRT:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] > stackMemory[ESP + 1]);
             break;
         // x >= y
         case FJP::OPRType::OPR_GRT_EQ:
             ESP--;
             stackMemory[ESP] = (stackMemory[ESP] >= stackMemory[ESP + 1]);
             break;
     }
 }
References FJP::RuntimeErrors::ERROR_01, FJP::RuntimeErrors::ERROR_02, FJP::exitProgramWithError(), FJP::OPR_DIV, FJP::OPR_EQ, FJP::OPR_GRT, FJP::OPR_GRT_EQ, FJP::OPR_INVERT_VALUE, FJP::OPR_LESS, FJP::OPR_LESS_EQ, FJP::OPR_MINUS, FJP::OPR_MOD, FJP::OPR_MUL, FJP::OPR_NEQ, FJP::OPR_ODD, FJP::OPR_PLUS, and FJP::OPR_RET.
execute_SIO()
void FJP::VirtualMachine::execute_SIO (int l, int m) private
Executes the SIO instruction.
The SIO instruction executes a system I/O operation based on the its m value. m = 0 -> prints the value on the top of the stack out to the screen m = 1 -> reads the value from the user and pushes it onto the stack m = 2 -> halts the system (the program terminates)
Parameters
l unused
m type of the i/O operation
Definition at line 358 of file vm.cpp.
{
     // Just so the compiler doesn't complain about an unused value.
     (void)l;
     // Perform an I/O operation
     switch (m) {
         // write
         case FJP::SIO_TYPE::SIO_WRITE:
             std::cout << stackMemory[ESP] << '\n';
             ESP--;
             break;
         // read
         case FJP::SIO_TYPE::SIO_READ:
             if (ESP == STACK_SIZE) {
                 FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
             }
             ESP++;
             std::cin >> stackMemory[ESP];
             break;
         // halt
         case FJP::SIO_TYPE::SIO_HALT:
             halt = 0;
             break;
         default:
             break;
     }
 }
References FJP::RuntimeErrors::ERROR_00, FJP::exitProgramWithError(), FJP::SIO_HALT, FJP::SIO_READ, and FJP::SIO_WRITE.
execute_STA()
void FJP::VirtualMachine::execute_STA (int l, int m) private
Executes the STA instruction.
The STA instruction stores a value at a certain address. The number as well as the address are meant to be pushed onto the stack beforehand (the address is pushed before the value)
Parameters
l level/depth of the target address
m unused
Definition at line 335 of file vm.cpp.
{
     // Just so the compiler doesn't complain about an unused value.
     (void)m;
     // Make sure that there are at least two values
     // on the stack - the value and the address
     if (ESP < 2) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Calculate the address within the corresponding frame.
     int frameAddress = base(l, EBP) + stackMemory[ESP - 1];
     // Make sure the target address exists within the stack.
     if (frameAddress > ESP || frameAddress < 0) {
         FJP::exitProgramWithError(FJP::RuntimeErrors::ERROR_00, ERROR_CODE);
     }
     // Store the value from the top of the stack at the address.
     stackMemory[frameAddress] = stackMemory[ESP];
     ESP -= 2;
 }
References FJP::RuntimeErrors::ERROR_00, and FJP::exitProgramWithError().
execute_STO()
void FJP::VirtualMachine::execute_STO (int l, int m) private
Executes the STO instruction.
The STO instruction stores the value from the top of the stack to a certain address within the stack.
Parameters
l depth/level of the symbol (address)
m address of the symbol
Definition at line 264 of file vm.cpp.
{
     // Stores the value at the address.
     stackMemory[base(l, EBP) + m] = stackMemory[ESP];
     ESP--;
 }
fetch()
void FJP::VirtualMachine::fetch () private
Fetches the next instruction to be executed.
Definition at line 66 of file vm.cpp.
{
     // Fetch the very next instruction from the code.
     instruction = (*program)[EIP];
     EIP++;
 }
getInstance()
FJP::VirtualMachine * FJP::VirtualMachine::getInstance () static
Returns the instance of the VirtualMachine class.
Returns
the instance of the class
Definition at line 9 of file vm.cpp.
{
     if (instance == nullptr) {
         instance = new VirtualMachine;
     }
     return instance;
 }
References instance, and VirtualMachine().
Referenced by main().
init()
void FJP::VirtualMachine::init () private
Initializes the virtual machine - sets the registers, clears out the stack, and so on.
Definition at line 51 of file vm.cpp.
{
     ESP  = 0; // stack pointer
     EBP  = 1; // base pointer
     EIP  = 0; // instruction pointer
     halt = 1; // flag if the virtual machine is halted or not
     // Number of functions that have been called = 0.
     // No function has been called yet.
     returnAddressCount = 0;
     // Clear out the entire stack as well as the return addresses.
     memset(returnAddresses, 0, sizeof(returnAddresses));
     memset(stackMemory, 0, sizeof(stackMemory));
 }
operator=()
void FJP::VirtualMachine::operator= (VirtualMachine const &) private delete
Deleted assign operator of the class.
Member Data Documentation
debug
bool FJP::VirtualMachine::debug private
flag pass in from the main function - create the stack trace output file or not
Definition at line 33 of file vm.h.
EBP
int FJP::VirtualMachine::EBP private
base pointer
Definition at line 30 of file vm.h.
EIP
int FJP::VirtualMachine::EIP private
instruction pointer
Definition at line 31 of file vm.h.
ERROR_CODE
constexpr int FJP::VirtualMachine::ERROR_CODE = 3 static constexpr private
error code of the VM (runtime exception)
Definition at line 19 of file vm.h.
ESP
int FJP::VirtualMachine::ESP private
stack pointer
Definition at line 29 of file vm.h.
halt
int FJP::VirtualMachine::halt private
flag indicating the end of the program
Definition at line 32 of file vm.h.
instance
FJP::VirtualMachine * FJP::VirtualMachine::instance = nullptr static private
the instance of the VirtualMachine class
Definition at line 24 of file vm.h.
Referenced by getInstance().
instruction
FJP::Instruction FJP::VirtualMachine::instruction private
current instruction
Definition at line 34 of file vm.h.
OUTPUT_FILE
constexpr const char* FJP::VirtualMachine::OUTPUT_FILE = "stacktrace.txt" static constexpr private
name of the output file
Definition at line 21 of file vm.h.
outputFile
std::ofstream FJP::VirtualMachine::outputFile private
output file (stream) - stack trace
Definition at line 36 of file vm.h.
program
FJP::GeneratedCode* FJP::VirtualMachine::program private
program to be executed (input data of the virtual machine)
Definition at line 35 of file vm.h.
returnAddressCount
int FJP::VirtualMachine::returnAddressCount private
number of return addresses stored in the list
Definition at line 28 of file vm.h.
returnAddresses
int FJP::VirtualMachine::returnAddresses[STACK_SIZE] private
list of return addresses
Definition at line 27 of file vm.h.
STACK_SIZE
constexpr int FJP::VirtualMachine::STACK_SIZE = 1024 static constexpr private
size of the virtual stack (1 KB)
Definition at line 18 of file vm.h.
stackMemory
int FJP::VirtualMachine::stackMemory[STACK_SIZE] private
internal stack used to perform operations as defined in the program
Definition at line 26 of file vm.h.
The documentation for this class was generated from the following files:
include/vm.h
src/vm.cpp