KIV/FJP Compiler: FJP::Lexer Class Reference
FJP::Lexer Class Reference
This class implements the functionality of a lexer.
#include <lexer.h>
Public Member Functions
void init (std::string filename, bool debug=false) override
Initializes the lexer.
FJP::Token getNextToken () override
Returns the next token.
void returnToPreviousToken () override
Goes back one token within the stream of tokens.
Static Public Member Functions
static Lexer * getInstance ()
Returns the instance of the class.
Private Member Functions
Lexer ()
Construction - creates an instance of the class.
Lexer (Lexer &)=delete
Delete copy constructor of the class.
void operator= (Lexer const &)=delete
Delete assign operator of the class.
void processAllTokens (bool debug)
Processes all tokens.
FJP::Token parseNextToken ()
Parses a next token.
void skipWhiteCharacters ()
Skips all white characters in the input file.
void skipComments ()
Skips all comments in the input file.
std::string getValue (int(validation_fce)(int))
Keeps consuming characters from the input file as long as the validation_fce is satisfied.
bool isEndOfFile () const
Returns true/false depending on whether the whole input file has been processed or not.
Private Attributes
long currentCharIndex
Current index (pointer) within the source input file (which character is currently being processed)
int currentLineNumber
Current line within the input file, so we can keep track of which token is on which line.
std::string fileContent
The content of the input file.
std::list< Token > tokens
List of all tokens extracted from the input file.
std::list< Token >::const_iterator currentTokenIt
Iterator used to send tokens off to the parser when requested.
std::unordered_set< std::string > alphabetic_keywords
Helper set of alphabetic keywords of the language.
Static Private Attributes
static constexpr int ERR_CODE = 1
Lexer error code (used when terminating the application).
static constexpr const char * OUTPUT_FILE = "tokens.json"
Output file containing tokens in a JSON format.
static constexpr const char * COMMENT_START = "/*"
Characters used to indicate the start of a comment.
static constexpr const char * COMMENT_END = "*/"
Characters used to indicate the end of a comment.
static constexpr int MAX_IDENTIFIER_LEN = 16
Maximum allowed length of an identifier.
static Lexer * instance = nullptr
The instance of the class.
Detailed Description
This class implements the functionality of a lexer.
It takes an input file and converts it into a stream of tokens which are then consumed by the parser.
Definition at line 14 of file lexer.h.
Constructor & Destructor Documentation
Lexer() [1/2]
FJP::Lexer::Lexer () private
Construction - creates an instance of the class.
Definition at line 26 of file lexer.cpp.
                 : currentCharIndex(0), currentLineNumber(0) {
     // Sort all the program keywords by their length. This is done
     // because we want to parse longer keywords first. For example,
     // we don't want to parse ':=' as ':' and '=' but we want to
     // parse it as ':='.
     sort(keywords.begin(), keywords.end(), [&](const auto &keyword_A, const auto &keyword_B) {
         return keyword_A.first.length() > keyword_B.first.length();
     });
     // Create a list of all alphabetic keywords such as 'goto', 'for', etc.
     for (const auto &keyword : keywords) {
         if (std::all_of(std::begin(keyword.first), std::end(keyword.first), [](char c) { return std::isalpha(c); })) {
             alphabetic_keywords.insert(keyword.first);
         }
     }
 }
References alphabetic_keywords, and FJP::keywords.
Referenced by getInstance().
Lexer() [2/2]
FJP::Lexer::Lexer (Lexer &) private delete
Delete copy constructor of the class.
Member Function Documentation
getInstance()
FJP::Lexer * FJP::Lexer::getInstance () static
Returns the instance of the class.
Returns
the instance of the class
Definition at line 19 of file lexer.cpp.
{
     if (instance == nullptr) {
         instance = new Lexer;
     }
     return instance;
 }
References instance, and Lexer().
Referenced by main().
getNextToken()
FJP::Token FJP::Lexer::getNextToken () override virtual
Returns the next token.
All tokens have been parsed beforehand and they are no trodden as a stream. This method is called by the parser when performing a recursive descent.
Returns
the next token in the stream of tokens.
Implements FJP::ILexer.
Definition at line 64 of file lexer.cpp.
{
     // If the parse requests another token while it's
     // already an end of file, it's an error
     if (currentTokenIt == tokens.end()) {
         FJP::exitProgramWithError(FJP::CompilationErrors::ERROR_00, ERR_CODE);
     }
     // Return the current token to the parser move on to the next token.
     Token token = *currentTokenIt;
     ++currentTokenIt;
     return token;
 }
References FJP::CompilationErrors::ERROR_00, and FJP::exitProgramWithError().
getValue()
std::string FJP::Lexer::getValue (int(validation_fce)(int)) private
Keeps consuming characters from the input file as long as the validation_fce is satisfied.
For example, this is used when parsing numbers or variable names - keep consuming characters as long as they are digits. param validation_fce validation function used to consume characters
Returns
the result of the consumption of the input characters (name, number, ...)
Definition at line 215 of file lexer.cpp.
{
     std::string value = "";
     // Keep consuming the characters as long as the validation
     // function is satisfied.
     while (!isEndOfFile() && validation_fce(fileContent[currentCharIndex])) {
         value += fileContent[currentCharIndex];
         currentCharIndex++;
     }
     return value;
 }
init()
void FJP::Lexer::init (std::string filename, bool debug = false) override virtual
Initializes the lexer.
It reads up the content of the input file and initializes all variables needed for parsing it.
Parameters
filename path to the input file (source code)
debug if this flag is on, the tokens will be output into a file in a JSON format.
Implements FJP::ILexer.
Definition at line 43 of file lexer.cpp.
{
     // Initialize variables.
     currentLineNumber = 0;
     currentCharIndex = 0;
     tokens.clear();
     // Terminate the application if the input file cannot be open.
     std::ifstream file(filename);
     if (file.is_open() == false) {
         FJP::exitProgramWithError(FJP::IOErrors::ERROR_00, ERR_CODE);
     }
     // Read the content of the input file (source code).
     fileContent = std::string((std::istreambuf_iterator<char>(file)),(std::istreambuf_iterator<char>()));
     // Parse the input file and sets the token iterator
     // to the first token, so it can be consumed by the parser.
     processAllTokens(debug);
     currentTokenIt = tokens.begin();
 }
References FJP::IOErrors::ERROR_00, and FJP::exitProgramWithError().
isEndOfFile()
bool FJP::Lexer::isEndOfFile () const private
Returns true/false depending on whether the whole input file has been processed or not.
Returns
true/false - depending on whether it's the end of file.
Definition at line 123 of file lexer.cpp.
{
     return currentCharIndex >= static_cast<long>(fileContent.length());
 }
operator=()
void FJP::Lexer::operator= (Lexer const &) private delete
Delete assign operator of the class.
parseNextToken()
FJP::Token FJP::Lexer::parseNextToken () private
Parses a next token.
This method is periodically used in the processAllTokens method.
Returns
next token that was parsed from the input file.
Definition at line 127 of file lexer.cpp.
{
     std::string tokenValue;
     // Skip all comments if there are any.
     skipComments();
     // Go through all the keywords in descending order (by their length)
     for (auto &keyword : keywords) {
         // Check if the current keyword would fit into the file (it doesn't exceed the file length)
         if (currentCharIndex + keyword.first.length() > fileContent.length())
             continue;
         // Check if it's indeed the keyword.
         tokenValue = fileContent.substr(currentCharIndex, keyword.first.length());
         if (tokenValue == keyword.first) {
             // Move on by the keyword length in the input file.
             currentCharIndex += tokenValue.length();
             // Check if the keyword is not just a prefix of a custom
             // identifier such as a variable or an array.
             if (alphabetic_keywords.count(tokenValue)) {
                 if (currentCharIndex < static_cast<long>(fileContent.length()) && is_part_of_identifier(fileContent[currentCharIndex])) {
                     currentCharIndex -= tokenValue.length();
                     continue;
                 }
             }
             // If a keyword has been found, skip all the white spaces
             // and return the token.
             skipWhiteCharacters();
             return {
                     keyword.second,   // type of the token
                     tokenValue,       // value of the token
                     currentLineNumber // number of the line the token is on
             };
         }
     }
     // If it's not a keyword, check if it's a number
     if (isdigit(fileContent[currentCharIndex])) {
         // If it is a digit, get all the following digits as well
         // until you find a non-digit character.
         std::string number = getValue(&isdigit);
         // Check if the digit is not too long (it fits into the datatype).
         if (atoi(number.c_str()) < 0) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_02, ERR_CODE, currentLineNumber);
         }
         // Skip all the white spaces and return the token.
         skipWhiteCharacters();
         return {
                 NUMBER,           // type of the token
                 number,           // value of the token
                 currentLineNumber // number of the line the token is on
         };
     }
     // It's not a keyword nor a number, it has to be an identifier.
     if (is_start_of_identifier(fileContent[currentCharIndex])) {
         // Consume all characters that belong to the identifier.
         std::string identifier = getValue(&is_part_of_identifier);
         // Check if the identifier doesn't exceed the maximum length.
         if (identifier.length() > MAX_IDENTIFIER_LEN) {
             FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_03, ERR_CODE, currentLineNumber);
         }
         // Skip all the white spaces and return the token.
         skipWhiteCharacters();
         return {
                 IDENTIFIER,       // type of the token
                 identifier,       // value of the token
                 currentLineNumber // number of the line the token is on
         };
     }
     std::cout << fileContent[currentCharIndex];
     // If the program gets to this point, it's an unknown character.
     FJP::exitProgramWithError(__FUNCTION__, FJP::CompilationErrors::ERROR_04, ERR_CODE, currentLineNumber);
     // Just so the compiler doesn't complain about a missing return value.
     return {};
 }
References FJP::CompilationErrors::ERROR_02, FJP::CompilationErrors::ERROR_03, FJP::CompilationErrors::ERROR_04, FJP::exitProgramWithError(), FJP::IDENTIFIER, is_part_of_identifier(), is_start_of_identifier(), FJP::keywords, and FJP::NUMBER.
processAllTokens()
void FJP::Lexer::processAllTokens (bool debug) private
Processes all tokens.
It goes thought the input file in order to parse it into tokens.
Parameters
debug flag if we want to output the tokens into a JSON format
Definition at line 87 of file lexer.cpp.
{
     Token token;
     std::stringstream ss;
     std::ofstream outputJSONFile;
     // If the debug is on, create the output file (tokens.json)
     if (debug == true) {
         outputJSONFile = std::ofstream(OUTPUT_FILE);
         // If there's an error while opening the output file, terminate the application.
         if (outputJSONFile.is_open() == false) {
             FJP::exitProgramWithError(FJP::IOErrors::ERROR_01, ERR_CODE);
         }
     }
     // Parse the entire input file token by token.
     ss << "[";
     if (fileContent.size() > 0) {
         while (isEndOfFile() == false) {
             token = parseNextToken();
             tokens.push_back(token);
             ss << token << ",\n";
         }
         ss.seekp(-2, std::ios_base::end);
     }
     ss << "]";
     // If the debug flag is on, store all tokens into the output file.
     // The format of the output file is JSON.
     if (debug == true) {
         outputJSONFile << ss.str();
         outputJSONFile.close();
     }
 }
References FJP::IOErrors::ERROR_01, and FJP::exitProgramWithError().
returnToPreviousToken()
void FJP::Lexer::returnToPreviousToken () override virtual
Goes back one token within the stream of tokens.
Implements FJP::ILexer.
Definition at line 77 of file lexer.cpp.
{
     // We're already at the very for token.
     if (currentTokenIt == tokens.begin()) {
         FJP::exitProgramWithError(FJP::CompilationErrors::ERROR_05, ERR_CODE);
     }
     // Move back one step within the stream of tokens.
     --currentTokenIt;
 }
References FJP::CompilationErrors::ERROR_05, and FJP::exitProgramWithError().
skipComments()
void FJP::Lexer::skipComments () private
Skips all comments in the input file.
Definition at line 249 of file lexer.cpp.
{
     // First off, skip all possible white characters.
     skipWhiteCharacters();
     std::string commentStart(COMMENT_START);
     std::string commentEnd(COMMENT_END);
     // Make sure we're not at the end of the file (that there's still enough room for a comment).
     if (currentCharIndex + commentStart.length() >= fileContent.length())
         return;
     // Check if the next two characters make up the start sequence of a comment.
     std::string characterPair = fileContent.substr(currentCharIndex, commentStart.length());
     if (characterPair != commentStart)
         return;
     // Keep counting open comments.
     int openComments = 1;
     currentCharIndex += commentStart.length();
     while (openComments > 0) {
         // Skip all white spaces.
         skipWhiteCharacters();
         // If we reach the end of the file and there's still an unclosed comment, it's an error.
         if (currentCharIndex + commentStart.length() > fileContent.length()) {
             FJP::exitProgramWithError(FJP::CompilationErrors::ERROR_01, ERR_CODE);
         }
         // Parse the next two characters.
         characterPair = fileContent.substr(currentCharIndex, commentStart.length());
         // Check if it's an opening of another comment,
         // closing sequence, or neither.
         if (characterPair == commentStart) {
             openComments++;
             currentCharIndex += commentStart.length();
         } else if (characterPair == commentEnd) {
             openComments--;
             currentCharIndex += commentStart.length();
         } else {
             currentCharIndex++;
         }
     }
     // Skip all white spaces.
     skipWhiteCharacters();
 }
References FJP::CompilationErrors::ERROR_01, and FJP::exitProgramWithError().
skipWhiteCharacters()
void FJP::Lexer::skipWhiteCharacters () private
Skips all white characters in the input file.
Definition at line 238 of file lexer.cpp.
{
     // Skip all white spaces.
     while (isspace(fileContent[currentCharIndex])) {
         // Keep counting the lines as you skip the white spaces.
         if (fileContent[currentCharIndex] == '\n') {
             currentLineNumber++;
         }
         currentCharIndex++;
     }
 }
Member Data Documentation
alphabetic_keywords
std::unordered_set<std::string> FJP::Lexer::alphabetic_keywords private
Helper set of alphabetic keywords of the language.
It is used to find keywords in the input file.
Definition at line 55 of file lexer.h.
Referenced by Lexer().
COMMENT_END
constexpr const char* FJP::Lexer::COMMENT_END = "*/" static constexpr private
Characters used to indicate the end of a comment.
Definition at line 27 of file lexer.h.
COMMENT_START
constexpr const char* FJP::Lexer::COMMENT_START = "/*" static constexpr private
Characters used to indicate the start of a comment.
Definition at line 24 of file lexer.h.
currentCharIndex
long FJP::Lexer::currentCharIndex private
Current index (pointer) within the source input file (which character is currently being processed)
Definition at line 37 of file lexer.h.
currentLineNumber
int FJP::Lexer::currentLineNumber private
Current line within the input file, so we can keep track of which token is on which line.
Definition at line 41 of file lexer.h.
currentTokenIt
std::list<Token>::const_iterator FJP::Lexer::currentTokenIt private
Iterator used to send tokens off to the parser when requested.
Definition at line 51 of file lexer.h.
ERR_CODE
constexpr int FJP::Lexer::ERR_CODE = 1 static constexpr private
Lexer error code (used when terminating the application).
Definition at line 17 of file lexer.h.
fileContent
std::string FJP::Lexer::fileContent private
The content of the input file.
TODO it'd be better if the file was read as a stream instead.
Definition at line 45 of file lexer.h.
instance
FJP::Lexer * FJP::Lexer::instance = nullptr static private
The instance of the class.
Definition at line 33 of file lexer.h.
Referenced by getInstance().
MAX_IDENTIFIER_LEN
constexpr int FJP::Lexer::MAX_IDENTIFIER_LEN = 16 static constexpr private
Maximum allowed length of an identifier.
Definition at line 30 of file lexer.h.
OUTPUT_FILE
constexpr const char* FJP::Lexer::OUTPUT_FILE = "tokens.json" static constexpr private
Output file containing tokens in a JSON format.
Definition at line 20 of file lexer.h.
tokens
std::list<Token> FJP::Lexer::tokens private
List of all tokens extracted from the input file.
Definition at line 48 of file lexer.h.
The documentation for this class was generated from the following files:
include/lexer.h
src/lexer.cpp